### ISSUE TITLE
Redundant package import

### ISSUE THREAD

**Issue by Pete1232** [disneystreaming/smithy4s#101]
Using Smithy `0.12.1`. Found this as the package import being generated is causing compilation errors because of our project structure. Can work around it but I don't think there's a reason for the package import to be added? Doesn't happen in all cases, seems to be if the namespace being imported entirely contains the other it works fine, otherwise the package import is added.

Example:

`errors.smithy`
```
namespace com.example.smithy.errors

@error("client")
@httpError(404)
structure NotFoundError {
  error: String,
}
```
`example.smithy`
```
namespace com.example.smithy.api

service ExampleService {
  operations: [ExampleOperation],
  errors: [com.example.smithy.errors#NotFoundError],
}

@http(method: "GET", uri: "/example", code: 200)
operation ExampleOperation {
  input: ExampleInput,
  output: ExampleOutput,
  errors: [com.example.smithy.errors#NotFoundError],
}

@input
structure ExampleInput {
  @httpQuery("id")
  id: String
}

@output
structure ExampleOutput {
  id: String
}
```

The generated `ExampleService.scala` has a package import for the namespace with the error models:
```
import ExampleServiceGen.ExampleOperationError
import com.example.smithy.errors
import com.example.smithy.errors.NotFoundError
import smithy4s.syntax._

trait ExampleServiceGen[F[_, _, _, _, _]] {
```

**Comment by lewisjkl** [comment]
Thanks for reporting this @Pete1232. I will be having a look at this today and will hopefully have a fix out for you by tomorrow at the latest.

**Comment by Baccata** [comment]
I released 0.12.2 this morning, containing the fix. Let us know if it works out

**Comment by Pete1232** [comment]
Thanks @Baccata . I gave it a go this morning and it looks good now, the import wasn't added. Thanks both for the quick turnaround

**Comment by Baccata** [comment]
Our pleasure 😄
