### ISSUE TITLE
Using http2 with ember server causes requests to hang

### ISSUE THREAD

**Issue by wunderk1nd-e** [disneystreaming/smithy4s#1017]
Hi there,

I've noticed that when making http2 requests (with TLS or plaintext) to a smithy endpoint using ember the requests just hang.
I've created a reproducer repo [here](https://github.com/wunderk1nd-e/smithy4shttp2bugreproducer) and you can see the test run [here](https://github.com/wunderk1nd-e/smithy4shttp2bugreproducer/actions/runs/5221035443/jobs/9424824161).

The tests run for http (plaintext), https, http2 (plaintext with prior knowledge) and http2 with TLS.

**Comment by Baccata** [comment]
Closing, this is an http4s issue : https://github.com/http4s/http4s/issues/7146 

Thanks for the repro :)

**Comment by armanbilge** [comment]
@wunderk1nd-e Hopefully fixed in v0.23.20, if not please let us know! Thanks :)

https://github.com/http4s/http4s/releases/tag/v0.23.20

**Comment by wunderk1nd-e** [comment]
> @wunderk1nd-e Hopefully fixed in v0.23.20, if not please let us know! Thanks :)
> 
> 
> 
> https://github.com/http4s/http4s/releases/tag/v0.23.20

Thanks a bunch !!!
I'll give it a spin in the morning.
