### ISSUE TITLE
Generated code doesn't compile when there's a smithy shape using a reserved name

### ISSUE THREAD

**Issue by miguel-vila** [disneystreaming/smithy4s#1051]
for example this smithy code:

```smithy
$version: "2.0"

namespace smithy4s.example.reservedNameOverride

use smithy4s.api#simpleRestJson

@simpleRestJson
service ReservedNameOverrideService {
    version: "1.0.0",
    operations: [SetOp]
}

@http(method: "POST", uri: "/api/set/", code: 204)
operation SetOp {
    input := {
       @required
       set: Set
    }
}

structure Set {
    @required
    someField: String,
    @required
    otherField: Integer
}
```

generates this code which doesn't compile:

```scala
package smithy4s.example.reservedNameOverride

import smithy4s.Schema
import smithy4s.Hints
import smithy4s.ShapeId
import smithy4s.schema.Schema.struct
import smithy4s.ShapeTag

case class SetOpInput(set: _Set)
object SetOpInput extends ShapeTag.Companion[SetOpInput] {
  val id: ShapeId = ShapeId("smithy4s.example.reservedNameOverride", "SetOpInput")

  val hints : Hints = Hints(
    smithy.api.Input(),
  )

  implicit val schema: Schema[SetOpInput] = struct(
    _Set.schema.required[SetOpInput]("set", _.set).addHints(smithy.api.Required()),
  ){
    SetOpInput.apply
  }.withId(id).addHints(hints)
}
```

because it's referring to `_Set` instead of `Set` in the same package

reproduced at #1050

**Comment by kubukoz** [comment]
related: https://github.com/disneystreaming/smithy4s/issues/389

**Comment by Baccata** [comment]
Wanna have a go at fixing ?

**Comment by miguel-vila** [comment]
@Baccata yeah, will give it a go, any hint on the related code parts?

**Comment by Baccata** [comment]
not off the top of my head

**Comment by kubukoz** [comment]
`CollisionAvoidance.scala` is probably your man.

**Comment by miguel-vila** [comment]
btw, what is the preferred solution here? to override the name (e.g. make it `case class SetOpInput(set: Set)` in the code above and `Set` refers to the type in the same package)? or to use the new name (make it `case class SetOpInput(set: _Set)`)? My thinking is that it's better to avoid name overriding

**Comment by Baccata** [comment]
@miguel-vila, actually, I'll fix it. 

The "reservedNames" was there in the first iterations of smithy4s. In the last year, a much more robust mechanism was introduced by @yisraelU, so dropping the reserved "types" altogether is a better solution.

**Comment by Baccata** [comment]
https://github.com/disneystreaming/smithy4s/pull/1052/files

**Comment by Baccata** [comment]
Closing as the PRs fixing this have been merged.
