### ISSUE TITLE
Errors without stack trace

### ISSUE THREAD

**Issue by msinton** [disneystreaming/smithy4s#1070]
Is it possible to create errors that extend `NoStackTrace` ?

This will be an efficiency and cost saving measure if we can remove the stack trace from business errors

**Comment by daddykotex** [comment]
Hi @msinton , thanks for the issue

To be clear, do you mean that you'd like to have the errors you define in your Smithy spec to be code generated as Throwable without a stack trace? For example [this NotFoundError generated](https://github.com/disneystreaming/smithy4s/blob/series/0.18/modules/bootstrapped/src/generated/smithy4s/example/ServerError.scala#L10) for the [error defined in this spec](https://github.com/disneystreaming/smithy4s/blob/series/0.18/sampleSpecs/example.smithy#L134).

I'm a fan of stack traces, so if we were to do such a thing, it would probably be opt-in via a `meta` annotations, like [adtMember](https://github.com/disneystreaming/smithy4s/blob/series/0.18/modules/protocol/resources/META-INF/smithy/smithy4s.meta.smithy#L26) that you'd add on the error structures

**Comment by msinton** [comment]
Hi @daddykotex 

Yes, there are many cases where the stack trace adds no value for debugging because it is generated by validation for example. If we can remove the stack trace at source then it will also not be logged and will not percolate through the system.

I think opt-in is a good idea

**Comment by yisraelU** [comment]
@msinton Can this be closed ?

**Comment by Baccata** [comment]
Closing : this feature has been merged and will be released in version 0.18 which should happen sometime in the next couple months.
