### ISSUE TITLE
0.18: optional bodies and content-type

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1072]
Forgive me if this has already been discussed, but anyway:

I noticed that an operation without an output body, e.g.

```smithy
@http(method: "GET", uri: "/no-output")
@readonly
operation NoOutput {
}
```

ends up being:

```http
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 0
Date: Tue, 04 Jul 2023 
```

which makes sense and I think it's a change since 0.17.

However, when the optional has an optional output body:

```smithy
@http(method: "GET", uri: "/optional-output")
@readonly
operation OptionalOutput {
    output := {
        @httpPayload
        bod: String
    }
}
```

and that body is a `None`, the HTTP response has a content type:

```http
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 0
Content-Type: application/json
Date: Tue, 04 Jul 2023 
```

which doesn't seem right - there's no content and the response isn't valid JSON. Is this a bug?

Tested on `0.18.0-595-e8a6dc6`, made from [this commit](https://github.com/disneystreaming/smithy4s/tree/e8a6dc6d1d1d0cfd50de52d2b99be64a9c694a70), which is pretty fresh (here's [a diff against 0.18](https://github.com/disneystreaming/smithy4s/compare/e8a6dc6d1d1d0cfd50de52d2b99be64a9c694a70...series/0.18))

**Comment by daddykotex** [comment]
I think you've had the same question that I had, and it's essentially related to this piece of code: https://github.com/disneystreaming/smithy4s/pull/1071/files#diff-43a37ddbed23455fc5b1eb55a5bd8cec34a6f9c613f758a1f577e27e67761324R91

My understanding is that it is to have a behaviour that's as close as possible to what AWS has and that's the behaviour they've chosen
1. if the shape is unit, do nothing (no body / content-type is set)
2. if the shape is not unit, but it's empty (like `None` in your case), use and empty json object and set the content-type accordingly

**Comment by kubukoz** [comment]
> if the shape is not unit, but it's empty (like None in your case), **use an empty json object** and set the content-type accordingly

that's the thing, there's no JSON object in there.

**Comment by yisraelU** [comment]
@kubukoz I would have assumed the same , there should be.
IIUC the logic in place checks for null https://github.com/disneystreaming/smithy4s/blob/d99a7451dc1e655d5fba0b6ae985a1d78b00ab9e/modules/json/src/smithy4s/json/internals/JsonPayloadCodecCompilerImpl.scala#L60
however nulls are only written for missing optional fields when you opt in via the explicit null encoding feature

**Comment by Baccata** [comment]
It's more complicated than that. Nulls may also be written in the event of an optional httpPayload field, no matter the preference regarding explicit nulls.

**Comment by kubukoz** [comment]
How? The example I described above has no null. Perhaps if there are other members in the output...

**Comment by Baccata** [comment]
@kubukoz, were we talking about the SimpleRestJson protocol here ?

**Comment by kubukoz** [comment]
Yep
