### ISSUE TITLE
(AWS) 0.18: trouble using disk credentials

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1075]
I'm having two problems with disk credentials from AWS:

1. `fromDisk` is called too late

It's only used as the last fallback, meaning it's after EC2. This would be fine, except for the fact that EC2 tries to get the credentials by looking up the AWS metadata url (`http://169.254.169.254/latest/meta-data/iam/security-credentials/`), which simply times out for me on any kind of client I use. With Ember, it takes ~75 seconds, which is unacceptable (I'm not sure what makes it that number, the default request timeout seems to be 45 seconds).

Can we alleviate this pain by checking for an environment variable's existence before trying to make that call? (I didn't find any) Can we try to resolve some host using fs2-io?

2. Requests don't seem to work 😅 

This could be a "me" problem, but: even if I explicitly only use `fromDisk` or wait for the fallback chain, it results in failed requests.

Note: this occurs moments after I refresh my credentials file. I've confirmed that the right file is being used, as the creds being loaded from it by smithy4s match the file contents. I'm able to use the AWS CLI and the Java SDK with no issues.

DynamoDB `ListTables` (awsJson1_0):

```
// HTTP/1.1 400 Bad Request Headers(Server: Server, Date: Tue, 04 Jul 2023 , Content-Type: application/x-amz-json-1.0, Content-Length: 132, Connection: keep-alive, x-amzn-RequestId: J1TI0GAGJ9L86FRDA6VB4R6USVVV4KQNSO5AEMVJF66Q9ASUAAJG, x-amz-crc32: 3880715766) body="{"__type":"com.amazon.coral.service#UnrecognizedClientException","message":"The security token included in the request is invalid."}"
```

Kinesis `ListStreams` (awsJson1_1):

```
// HTTP/1.1 400 Bad Request Headers(x-amzn-RequestId: ff6e84d3-a804-3af7-a270-2905a509e1d0, x-amz-id-2: ej4c9XGHaw7gb3LWgBF3CXzOjBHh0Lwlwpw0EvLeUj0PLuIXRdlru5fbuGLEfI0p4quHdLFOPrSdlCh1BJQkLRg7gEayNPg8, Date: Tue, 04 Jul 2023 , Content-Type: application/x-amz-json-1.1, Content-Length: 107, Connection: close) body="{"__type":"UnrecognizedClientException","message":"The security token included in the request is invalid."}"
```

Lambda `ListFunctions` (restJson1):

```
// HTTP/1.1 403 Forbidden Headers(Date: Tue, 04 Jul 2023 , Content-Type: application/json, Content-Length: 68, Connection: keep-alive, x-amzn-RequestId: b9964074-646f-4c60-bf7c-302cdd194d0a, x-amzn-ErrorType: UnrecognizedClientException) body="{"message":"The security token included in the request is invalid."}"
```

This is on https://github.com/disneystreaming/smithy4s/tree/e8a6dc6d1d1d0cfd50de52d2b99be64a9c694a70 .

Update: if I use `AwsCredentials.Default` directly and pass the values I've found in the credentials file, it works. I think that's enough for me to investigate and fix this second issue.

Update 2: Looks like it might be a case sensitivity issue: the credentials loaded with `fromFile` are a lowercased version of what I see in the file.

**Comment by kubukoz** [comment]
another thing, I think disk creds should also use `refreshing`, because the file can change while you're using the client.

**Comment by Baccata** [comment]
> This would be fine, except for the fact that EC2 tries to get the credentials by looking up the AWS metadata url (http://169.254.169.254/latest/meta-data/iam/security-credentials/), which simply times out for me on any kind of client I use. 

A timeout should certainly be added to the client call [here](https://github.com/disneystreaming/smithy4s/blob/series/0.18/modules/aws-http4s/src/smithy4s/aws/AwsCredentialsProvider.scala#L131), as we cannot trust that the user will set a connection timeout  in their clients. 

> another thing, I think disk creds should also use refreshing, because the file can change while you're using the client.

I disagree that it should be default. Disk credentials should be like environment variables in that they ought to be considered static for the lifecycle of the application. If you want a refreshing disk provider, you have all the building blocks required to implement it.

**Comment by kubukoz** [comment]
Fair enough. I'll add that timeout in a PR.
