### ISSUE TITLE
Backport service.interpreter and friends to 0.17

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1111]
These have default implementations so it should be possible without breaking compat. It's encouraging a good pattern, so I think it won't hurt to push it before 0.18 is out.

Look here:

https://github.com/disneystreaming/smithy4s/blob/6f94491d0a3f215dd619aac7cbb4a9735ab943c5/modules/core/src/smithy4s/Service.scala#L129-L165

**Comment by Baccata** [comment]
Fine with it if someone on your side takes it on

**Comment by kubukoz** [comment]
absolutely

**Comment by kubukoz** [comment]
Closed in #1118.
