### ISSUE TITLE
@deprecated on mixin member generates invalid code

### ISSUE THREAD

**Issue by ghostbuster91** [disneystreaming/smithy4s#1121]
Deprecating mixin member causes the code generation to output invalid code. 
Tested with 0.17.12

Given:
```smithy
@mixin
structure Extra {
    @deprecated
    @required
    name: String
}

structure Greeting with [Extra] {
    @required
    message: String
}
```

actual generated code:
```scala
trait Extra {
  def @deprecated(message = "N/A", since = "N/A") name: String
}
```

expected generated code:
```scala
trait Extra {
  @deprecated(message = "N/A", since = "N/A") 
  def name: String
}
```

Full code to reproduce the issue can be found here https://github.com/ghostbuster91/demos/tree/deprecated-issue-mixin

**Comment by kubukoz** [comment]
closed in #1123 and released in 0.17.13, for reasons unknown github (or github refined, idk) can't tell that the PR is part of that tag.
