### ISSUE TITLE
IntEnum Trait "Does Not Take Parameters" Error

### ISSUE THREAD

**Issue by etspaceman** [disneystreaming/smithy4s#1136]
Given a trait defined as:

```
@trait(selector: ":is(string, blob, member:test( > :is(string, blob)))")
intEnum someTrait {
    FIRST = 1,
    SECOND = 2,
    THIRD = 3,
    FOURTH = 4,
    FIFTH = 5
}
```

And a usage defined as:

```
@someTrait(5)
string SomeString
```

Errors are received when generating:

```
SomeTrait.type does not take parameters
SomeTrait(5)
```

Seems it should be using `SomeTrait.FIFTH` rather than `SomeTrait(5)` (or something similar).

**Comment by lewisjkl** [comment]
Thanks for reporting, I should have some time to look at this tomorrow and will report back with what I find and hopefully a PR to fix.

**Comment by kubukoz** [comment]
Does this affect normal enums too?

**Comment by etspaceman** [comment]
I suspect that it does but I have not tested it

**Comment by lewisjkl** [comment]
I'll test that out too while I'm at it.
