### ISSUE TITLE
Add a pre-processor for removing constraints from shapes in the `com.amazon` namespaces 

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#1142]
As Smithy4s evolves to take on the role of an AWS SDK, we need to be wary of potential warts of AWS. In particular, although some constraints seem to be present in the AWS specs found in the [javascript SDK repo](https://github.com/aws/aws-sdk-js-v3), they seem to not be completely respected by the AWS services. 

Considering we cannot easily ignore constraints in our interpreters, it feels like a safer bet to just remove the constraints at build time (at least length/range constraints) in order to ensure that the AWS clients we derive in smithy4s do not raise errors when AWS doesn't respect its own constraints. AWS even states that [constraints should not be enforced when deserialising an output](https://smithy.io/2.0/spec/constraint-traits.html?highlight=constraints#constraint-trait-enforcement) 

NB : one of the reasons we cannot easily disable validation of response deserialisation is that the mechanism that constraints are implemented with is the same as [type refinements](https://disneystreaming.github.io/smithy4s/docs/codegen/customisation/refinements). Refinements require a partial type transformation `A => Either[String, B]`, and disabling constraints would mean being able to dynamically test that the input type `A` and the output type `B` are one and the same, which we are not able to do with the current model. Changing the model is very impactful, and we want to reserve it for situations where we don't see any other possible solution. 

For a point of reference to this unit of work, head over to this PR : https://github.com/disneystreaming/smithy4s/pull/1110

**Comment by yisraelU** [comment]
I can take this

**Comment by Baccata** [comment]
@yisraelU, actually @zetashift has expressed a desire to take it on already

**Comment by zetashift** [comment]
@yisraelU ~heyho, yea I wanted to pick this up this weekend! However if you can do(and want to!) you can pick this up and I'll go straight for: https://github.com/disneystreaming/smithy4s/issues/1141~

~Does that sounds okay? If not let me know I'll just tackle this one first.~ I'll just pick it up, hopefully I won't have to ask too many questions!

**Comment by yisraelU** [comment]
@zetashift no problem
I'll pick up something else

**Comment by kubukoz** [comment]
I think this may have been done by @etspaceman in kinesis4cats, but not sure if it filters by AWS namespace or anything like that.

**Comment by etspaceman** [comment]
Kinesis4Cats fixes the refinement rather than removes it. So it only updates a few deser types. 

https://github.com/etspaceman/kinesis4cats/blob/main/smithy4s-client-transformers/src/main/scala/kinesis4cats/smithy4s/client/KinesisSpecTransformer.scala

**Comment by zetashift** [comment]
So I'm working on this, while looking at #1110 and wondering if my thought process sounds okay:

- create a new transformer like: `modules/codegen/src/smithy4s/codegen/transformers/AwsConstraintRemover.scala`
- The transformer removes things like `@length` from shapes in the `com.amazon` namespace
- Write tests to make sure they actually do that.

**Comment by Baccata** [comment]
Yup, that is the right way to go at it !
