### ISSUE TITLE
Services should not return bodies in responses of `HEAD` requests 

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#1145]
We've recently changed the logic in both the 0.17 and 0.18 lineages to autofill response bodies with `{}` under certain circumstances, in order to align with AWS semantics. 

This new behaviour is arguably incorrect in the context of `HEAD` requests, as the corresponding responses are not supposed to contain a body. 

On 0.17, the fix is tricky as the addition of an empty json object body is coupled to the entity decoder which doesn't have the information. We may have to resort some http4s-level middleware under the hood. 
On 0.18, the fix should be easier

**Comment by kubukoz** [comment]
Q: should this affect reponses with the NoContent status?

**Comment by Baccata** [comment]
Well, somebody's got an issue for it : https://github.com/disneystreaming/smithy4s/issues/1169

**Comment by kubukoz** [comment]
Not an accident :p
