### ISSUE TITLE
Add `withWrap` / `mapWrap` methods to endpoint builder

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1152]
Follow-up to https://github.com/disneystreaming/smithy4s/pull/1097 - currently, there are no methods for customizing the `wrap` method of the endpoint (which is the method that essentially wraps an endpoint input into an operation).

There might be an (arguably obscure) use-case for customizing `wrap`, so let's consider adding those, or use this ticket to document the reason against that.

Note: this isn't blocking for 0.18 because adding these concrete methods can be done without breaking BC.

**Comment by Baccata** [comment]
Can you formulate such a usecase ? 

In the meantime, here's my train of thought :

* A map modifying function would be of the shape `I => I`
* The only way to do that "lawfully" (ie without unsafe casts) would be via a `SchemaVisitor`  (or more generically, a `PolyFunction[Schema, A =>> A => A]`) 
* The `wrap` method's canonical use-site is client-side interpreters, which are written in terms of `SchemaVisitors`  (in part) 
* This kinda indicates that if there is such a transformation needs occurring, a good location for it would probably within the interpreter.

**Comment by kubukoz** [comment]
> Can you formulate such a usecase ?

not at the moment, I just wanted to have an issue or discussion as a record of us in case we don't consider this functionality useful ;)

Agree on the next two points. I was thinking in terms of a transformation on a concrete endpoint, but that doesn't seem useful for anything outside of testing with a very specific endpoint.

However, on these:

> The wrap method's canonical use-site is client-side interpreters, which are written in terms of SchemaVisitors (in part) 
> This kinda indicates that if there is such a transformation needs occurring, a good location for it would probably within the interpreter.

I mostly agree but you may not always be writing an interpreter of your own - you might want to wrap an existing one. Having to change a `SchemaVisitor` means you need to stop wrapping and do the internals yourself. However, this usecase is theoretical enough that I don't really think it's going to be an issue.

**Comment by Baccata** [comment]
This layer got an overhaul, the modification of the wrap methods should be easier without the need of specific methods. 

As a result, I'm closing this issue.
