### ISSUE TITLE
Scala 3: ClassCastException when encoding empty document arrays

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1158]
To reproduce:

```scala
//> using dep "com.disneystreaming.smithy4s::smithy4s-json:0.17.17"
//> using scala "3.3.0"
import smithy4s.Document
import smithy4s.schema.Schema

val capi = smithy4s.http.json.codecs()
val codec = capi.compileCodec(Schema.document)

println(
  new String(
    capi.writeToArray(
      codec,
      Document.array()
    )
  )
)

```

This throws:

```
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lsmithy4s.Document; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lsmithy4s.Document; is in unnamed module of loader java.net.URLClassLoader @7558c8ef)
	at smithy4s.http.json.SchemaVisitorJCodec$$anon$17.encodeValue(SchemaVisitorJCodec.scala:328)
	at smithy4s.http.json.SchemaVisitorJCodec$$anon$17.encodeValue(SchemaVisitorJCodec.scala:320)
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.write(JsonWriter.scala:934)
	at com.github.plokhotnyuk.jsoniter_scala.core.package$.writeToArray(package.scala:405)
	at smithy4s.http.json.JsonCodecAPI.writeToArray(JsonCodecAPI.scala:91)
	at repl.MdocSession$MdocApp.<init>(Main.worksheet.sc:26)
	at repl.MdocSession$.app(Main.worksheet.sc:3)

```

Affects Scala 3 only (2.13 is fine, at least). 

I did a quick check of a possible regression and:

- Works fine in 0.13.0 (the first release with the current Schema encoding) and 0.13.7 (the last 0.13 release)
- Breaks in [0.14.0](https://github.com/disneystreaming/smithy4s/releases/tag/v0.14.0) (didn't narrow it down to a specific PR but my guess is https://github.com/disneystreaming/smithy4s/pull/297 as it touched the relevant lines) and in the latest 0.17 release, 0,17.17.

**Comment by kubukoz** [comment]
Still breaks in 0.18 at https://github.com/disneystreaming/smithy4s/tree/9031f5a83dec50fc7be1b077f5ee72e2861f7cb2

```scala
//> using dep "com.disneystreaming.smithy4s::smithy4s-json:0.18.0-885-9031f5a"
//> using scala "3.3.0"
import smithy4s.json.Json
import smithy4s.Document

println(
  Json.writeDocumentAsPrettyString(Document.array())
)

```

**Comment by kubukoz** [comment]
Of all the things in the world, you can thank JIRA for this discovery.

**Comment by daddykotex** [comment]
> Of all the things in the world, you can thank JIRA for this discovery.

I'm curious what's the story there? Are you writing smithy specs to interact with a JIRA api?

**Comment by kubukoz** [comment]
Yeah, I'm toying with the idea of making a lightweight jira UI for just the parts I care about.

Wanted to get issues as `Document`s so that I wouldn't have to type anything yet, and bumped into this due to some empty array deeply inside.

**Comment by daddykotex** [comment]
maniac
