### ISSUE TITLE
No-Content responses should not contain content

### ISSUE THREAD

**Issue by mikeshepherd** [disneystreaming/smithy4s#1169]
When generating a No Content (204) response with `simpleRestJson` smithy4s generates an empty json object `{}` as content. 

This conflicts with the HTTP spec, and http4s ember server partially corrects this by not returning the content anyway. 
However it does not update the `Content-Length` header leaving a inconsistent response, one with a non-zero content-length, but 0 bytes of content. This can cause some http clients to timeout as they wait for the content that never comes.

I've recreated this here: https://gist.github.com/mikeshepherd/34ac82d3aba34be1428e7402ff521ae4. This will execute the same request twice, once with a genuine ember server and client, and once with a client created directly from the routes.

Arguably there are bugs in http4s (I'll be raising an issue here shortly), and the clients that fail in this situation as well, but it is also incorrect for smithy4s-http4s to be generating this body in the first place.

**Comment by daddykotex** [comment]
Fixed in 0.18
