### ISSUE TITLE
Prepare example project

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#119]
Should have a server, client, a CLI client once we publish that, (insert future integration here)...

**Comment by lewisjkl** [comment]
I have a super minimal example [here](https://github.com/lewisjkl/smithy4s-minimal-example) that we can use as a starting point for this, if it is helpful. We are probably going to want to showcase more features than I have in there though

**Comment by kubukoz** [comment]
fair nuff
