### ISSUE TITLE
Strange behavior in http4s URIs

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1232]
In this code:

```scala
//> using lib "com.disneystreaming.smithy4s::smithy4s-http4s:0.17.19"
import cats.effect.unsafe.IORuntime
import cats.effect.IO

import org.http4s.client.Client
import demo.DemoGen
import smithy4s.http4s.SimpleRestJsonBuilder
import demo.Demo
import org.http4s.Response
import cats.effect.kernel.Resource
import cats.implicits._
import cats.effect.implicits._

val c: Client[IO] = Client { req =>

  IO.println(req.uri).toResource *>
    Resource.pure(Response())
}

@main def run =
  SimpleRestJsonBuilder(Demo)
    .client(c)
    .make
    .toTry
    .get
    .getDemo()
    .unsafeRunSync()(IORuntime.global)
```

In 0.17.19, the captured URI is:

```
http://localhost:8080/demo
```

However, on the latest series/0.18 snapshot:

```scala
//localhost:8080/demo
```

That doesn't seem like a valid URL. I think we should dig into it before 0.18 hits shelves.

**Comment by kubukoz** [comment]
I think it boils down to this fragment:

https://github.com/disneystreaming/smithy4s/blob/8999582da6097dbd53cbfd62086dc7e9cf0295d5/modules/http4s-kernel/src/smithy4s/http4s/kernel/package.scala#L77-L80

not setting the `scheme`. This could result in `https` not working in clients, I suppose.

Edit: confirmed, a `.uri(...)` on client builders results in the protocol being ignored.

**Comment by Baccata** [comment]
Not sure why github didn't autoclose :/

**Comment by kubukoz** [comment]
It didn't reach the main branch (0.18) because I was targetting misc-polish.

**Comment by Baccata** [comment]
oh gotcha
