### ISSUE TITLE
Open enums: Dynamic support

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1243]
In #1137, open enum support was added. Unfortunately, the `DynamicModelCompiler` treats all enums as closed. I don't think this can be worked around in userland, because ultimately you end up having to go from `String` / `Int` to `A`, which is abstract to you.

I propose that we add a condition for `@openEnum` just like in the codegen, and produce open enum tags in these cases.

**Comment by Baccata** [comment]
Agreed
