### ISSUE TITLE
0.18.0 Getting schema instance for timestamp with DATE_TIME format

### ISSUE THREAD

**Issue by plokhotnyuk** [disneystreaming/smithy4s#1250]
[During migration of benchmarks for smithy4s-json](https://github.com/plokhotnyuk/jsoniter-scala/commit/17bd2f54ede49d944ce15ae39692714f3ad9e13d) I'm stuck with not being able to preserve `DATA_TIME` format for timestamps.

Having `Schema.timestamp` how to transform it into a schema that will be serialized with `TimestampFormat.DATE_TIME` using a codec derived by `Json.deriveJsonCodec`?

**Comment by Baccata** [comment]
Hey Andriy, hope you're well. Apologies for that, I was planning to PR jsoniter early next week to follow our release, but you're obviously super on top of things. Anyway, what you can do is : 

```scala
val datetime = Schema.timestamp.addHints(smithy.api.TimestampFormat.DATE_TIME)
```

and use that value everywhere you're using `timestamp`

**Comment by plokhotnyuk** [comment]
@Baccata Thanks for the quick response and your support! I'm happy to see your project evolving!

That was my first idea to use `DATE_TIME` as a hint, but the latest IntelliJ IDEA mislead me by the following error highlighting:
![image](https://github.com/disneystreaming/smithy4s/assets/890289/19bf20f8-8ca4-4818-ae6c-566022973e2b)

**Comment by plokhotnyuk** [comment]
The problem is that `val datetime = Schema.timestamp.addHints(smithy.api.TimestampFormat.DATE_TIME)` works fine with Scala 3 but doesn't compile for Scala 2:
```
[error] /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-benchmark/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/Smithy4sJCodecs.scala:25:61: overloaded method addHints with alternatives:
[error]   (hints: smithy4s.Hints)smithy4s.schema.Schema[smithy4s.Timestamp] <and>
[error]   (hints: smithy4s.Hint*)smithy4s.schema.Schema[smithy4s.Timestamp]
[error]  cannot be applied to (smithy.api.TimestampFormat.DATE_TIME.type)
[error]   private[this] val datetime: Schema[Timestamp] = timestamp.addHints(smithy.api.TimestampFormat.DATE_TIME)
[error] 
```

**Comment by Baccata** [comment]
Right, that's because Scala 2 is annoying with regards to type inference of ADT members. We generate a `.widen` method to mitigate the annoyance. The following should do the trick : 

```scala
val datetime = Schema.timestamp.addHints(smithy.api.TimestampFormat.DATE_TIME.widen)
```

**Comment by plokhotnyuk** [comment]
@Baccata Thanks a bunch! Finally it works as expected for both Scala versions.
