### ISSUE TITLE
DocumentDecoder does not support alloy.Untagged.

### ISSUE THREAD

**Issue by daddykotex** [disneystreaming/smithy4s#1273]
As per the title says. The DocumentEncoder supports it, so not supporting it in the DocumentDecoder means we can't round-trip in some cases.

**Comment by yisraelU** [comment]
@Baccata It seems this can be closed
(For context , I was looking for something to take on)

**Comment by Baccata** [comment]
Closed in https://github.com/disneystreaming/smithy4s/pull/1446, thanks for the ping @yisraelU
