### ISSUE TITLE
OpenAPI wrong string case

### ISSUE THREAD

**Issue by karadzhov** [disneystreaming/smithy4s#1287]
According to the [OpenAPI specification](https://swagger.io/docs/specification/authentication/bearer-authentication/) the property `components.securitySchemes."smithy.api.httpBearerAuth".scheme` must be lowercase "bearer" [instead of "Bearer"](https://github.com/disneystreaming/smithy4s/blob/series/0.18/modules/bootstrapped/resources/smithy4s.example.guides.auth.HelloWorldAuthService.json#L102).

I found this bug while debugging the code generated by the Dart OpenAPI generator which unfortunately does case sensitive comparison.

**Comment by Baccata** [comment]
This is a bug on the upstream library. I suggest you open an issue over there (or even better, propose a fix via a PR). Here's the line that needs to be amended : 

https://github.com/smithy-lang/smithy/blob/0fc277a6c05e300ec0e4df494df80fe2dcf99602/smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/security/HttpBearerConverter.java#L39 

I presume there may be tests to amend too, not 100% sure.

**Comment by karadzhov** [comment]
After some additional research, I've found out that the value must be a case-insensitive token according to the HTTP specification. [I've submitted an issue in the OpenAPI's repository](https://github.com/OpenAPITools/openapi-generator/issues/17073).

**Comment by Baccata** [comment]
Thanks for doing the research and reporting back !
