### ISSUE TITLE
Increase verbosity of "Multiple artifact manifests indicate containing generated code for namespace"

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1338]
This is a tiny QOL improvement for fixing misconfigured builds: specifying which artifact manifests have the actual problem.

The code in question:

https://github.com/disneystreaming/smithy4s/blob/14883016691c0eeea460a466cba1d67fab1139bc/modules/codegen/src/smithy4s/codegen/internals/CodegenImpl.scala#L137

While we don't have access to the exact jar paths here, `CodegenRecord.recordsFromModel` looks at metadata nodes from the model, which _should_ have a smithy `SourceLocation` attached. Transforming that, or even printing these locations verbatim, would be a good way to give users a hint.

For example:

1. Extend `CodegenRecord` with a `source: SourceLocation` field
2. Provide a value in `CodegenRecord.fromNode` based on `node.getSourceLocation()`
3. Reorganize the code in `alreadyGenerated` a little bit so that the locations can be attached to the exception message

**Comment by dwalend** [comment]
I'm working on a PR for this one. Inside the code braces things are going well.

How do I jink smithy4s to produce this error? Who sees it? How pretty does it need to be?

**Comment by dwalend** [comment]
Also should "Multiple artifact manifests indicate containing generated code for namespace ..." be something like "Multiple artifact manifests cannot contain generated code for namespaces ..." ?

**Comment by kubukoz** [comment]
> How do I jink smithy4s to produce this error? Who sees it? How pretty does it need to be?

In general, the mechanism that handles `CodegenRecord` is used in situations where you generate a subset of your datatypes in one module/library, and some others (that depend on the former) in another.

You can reproduce this by running `sbt compile` in https://github.com/kubukoz/demos/tree/smithy4s-multiple-indicate-generated , that repo should also clarify why we do this check in the first place / why it'd be a problem if we didn't

**Comment by kubukoz** [comment]
> Also should "Multiple artifact manifests indicate containing generated code for namespace ..." be something like "Multiple artifact manifests cannot contain generated code for namespaces ..." ?

I think each namespace could go into its own line.

Most importantly, I think, you want to know _which artifact manifests_ we're talking about. I think the approach I mentioned in the OP is still valid:

- in `CodegenRecord.recordsFromModel`, you have access to the full Smithy model, and the metadata entries that get decoded into `CodegenRecord`s
- the `fromNode` method in the same object has access to `node: Node`, which carries source information in `.getSourceLocation()`. This should be useful enough. We "just" need to put that into `CodegenRecord` as well, and print its values in the error message.

**Comment by kubukoz** [comment]
as far as tests go, I think this could be implemented as a [scripted sbt test](https://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html), it might be hard to test otherwise. Sample tests:

https://github.com/disneystreaming/smithy4s/tree/series/0.18/modules/codegen-plugin/src/sbt-test/codegen-plugin

I imagine the setup from the repro I posted could be copied to a `build.sbt` in there, and we'd somehow assert on the text of the error message, maybe with a [custom assertion](https://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html#step+6%3A+custom+assertion)...

if not, I guess we can "unit test" it by creating fake `Node` instances.

**Comment by dwalend** [comment]
I've got it to 

```bash
[info] set current project to root (in build file:/Users/dwalend/projects/demos/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 2 Scala sources to /Users/dwalend/projects/demos/b/target/scala-3.4.2/classes ...
[info] compiling 3 Scala sources to /Users/dwalend/projects/demos/a/target/scala-3.4.2/classes ...
[error] java.lang.IllegalStateException: Multiple artifact manifests cannot contain generated code for the same namespace:
[error]  ns is contained in jar:file:///Users/dwalend/projects/demos/a/target/scala-3.4.2/a_3-0.1.0-SNAPSHOT.jar!/META-INF/smithy/smithy4s.tracking.smithy [3, 31], jar:file:///Users/dwalend/projects/demos/b/target/scala-3.4.2/b_3-0.1.0-SNAPSHOT.jar!/META-INF/smithy/smithy4s.tracking.smithy [3, 31]
[error]         at smithy4s.codegen.internals.CodegenImpl$.generate(CodegenImpl.scala:181)
```

In that test project. Is that output useful? It does have a and b in it, burried in the .jar file paths.

No rush. I'll learn scripted sbt test next.

**Comment by kubukoz** [comment]
Seems useful to me :) it's not a particularly common situation to run into, but when you do run into it... it's good to have more info like that.

**Comment by dwalend** [comment]
I've got the scripted test part working fine. (Although it takes about 15 minutes to run the whole suite.)

I really think the right answer is a testable exception and a unit test. I'm building that.

(Was - I'm struggling with how to check the text of the output. I'm down to one bad approach - writing a custom log file, then checking for a magic string after the test runs. Do you want something that brittle?)

**Comment by dwalend** [comment]
I'm missing a step to have this in a unit test - I think one that gets more information into a .jar file manifest. Any thoughts on what that might be?

` test("namespace clash") {
    val aSmithy =
      """namespace nsa
        |
        |string Hello
        |
        |string GoodBye
        |""".stripMargin

    val bSmithy = """namespace nsb
                    |
                    |// no hello
                    |// string Hello
                    |//
                    |string GoodBye
                    |""".stripMargin

    val model = Model
      .assembler()
      .discoverModels()
      .addUnparsedModel("a.smithy", aSmithy)
      .addUnparsedModel("b.smithy", bSmithy)
      .assemble()
      .unwrap()
    
    //there has to be some other step to get a and b into metadata in a .jar file. 

    //should throw the expected exception
    TestUtils.generateScalaCode(model)
  }
`

**Comment by dwalend** [comment]
Back on the logging front - in that demo project you shared "is contained in" does appear right where I expected. Is logging somehow suppressed in smithy4s ? If I find where, is it OK for me to switch it to normal?

**Comment by kubukoz** [comment]
> Back on the logging front - in that demo project you shared "is contained in" does appear right where I expected. Is logging somehow suppressed in smithy4s ? If I find where, is it OK for me to switch it to normal?

I don't think it should be suppressed, _but_ if you log something in the part of the plugin that sets global settings, I think that gets silenced by sbt unless you use `debug`. Or something like that.

Apologies, not a lot of time to look into this and the PR recently :(

**Comment by dwalend** [comment]
\> Apologies, not a lot of time to look into this and the PR recently :(

No worries. My turn to take a vacation.
