### ISSUE TITLE
[Protocol Compliance ] Question: Url encoding and decoding

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#1425]
when working on tests for smithy4s-zio I bumped into a few cases in the [HttpLabel](https://github.com/smithy-lang/smithy/blob/367c4a5ac4f9bae217c0f00b45344f0872d7491d/smithy-aws-protocol-tests/model/restJson1/http-labels.smithy) suite where there seems to be a contradiction around the handling of the url input
- case 1 : https://github.com/smithy-lang/smithy/blob/367c4a5ac4f9bae217c0f00b45344f0872d7491d/smithy-aws-protocol-tests/model/restJson1/http-labels.smithy#L180
- case 2 : https://github.com/smithy-lang/smithy/blob/367c4a5ac4f9bae217c0f00b45344f0872d7491d/smithy-aws-protocol-tests/model/restJson1/http-labels.smithy#L260

case 1 led me to believe the url is encoded and therefore when creating the smithy model , one must decode, however in that case , in case 2 the plus sign would be converted to a space char.

The reason why the tests are passing is that http4s has a `plusIsSpace` boolean field and it's set to false.

However, I wonder, if this is a good thing, as perhaps other regex chars overlap with URL codecs .

My thoughts were without talking to AWS yet, is that the intention is to handle decoding only on a httpLabel basis

**Comment by Baccata** [comment]
I'm sorry, I'm gonna ask you to rephrase the question and link to some code or something because I honestly can't understand what you're asking 😞

**Comment by yisraelU** [comment]
Apologies, for the unclear question.
After further analysis, I think you are correct, the question is for AWS
