### ISSUE TITLE
LSP codegen: should probably use `sources` instead of `imports`

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1459]
As per https://smithy.io/2.0/guides/smithy-build-json.html#using-smithy-build-json:

> `imports` - Provides a list of model files and directories to load when validating and building the model. Imports are a local dependency: they are not considered part of model package being built, but are required to build the model package.

> `sources` - Provides a list of relative files or directories that contain the models that are considered the source models of the build. 

We currently generate `imports`.

**Comment by Baccata** [comment]
well let's change it then.
