### ISSUE TITLE
Broken link in 05-compliance-tests.md

### ISSUE THREAD

**Issue by meldmy** [disneystreaming/smithy4s#1472]
>  Refer to [this example](@GITHUB_BRANCH_URL@modules/compliance-tests/test/src/smithy4s/compliancetests/WeaverComplianceTest.scala) to see how we did it for `Weaver` in this project.

Hi guys, I found a broken link in the documentation reference to the nonexistent test in the codebase:
https://disneystreaming.github.io/smithy4s/docs/protocols/compliance-tests#testing-the-protocol

Here, I found you used @GITHUB_BRANCH_URL:
https://github.com/disneystreaming/smithy4s/blob/da4b23a68e2d03be4ac310d2aaca8ba755e79315/modules/docs/markdown/03-protocols/05-compliance-tests.md?plain=1#L51

**Comment by kubukoz** [comment]
Thanks for reporting!

I think the class is gone altogether, some of Weaver integration seems to live directly in https://github.com/disneystreaming/smithy4s/blob/series/0.18/modules/tests/src/smithy4s/tests/ProtocolComplianceSuite.scala

**Comment by kubukoz** [comment]
@meldmy would you like to submit a fix? (targetting the 0.18 branch)

**Comment by meldmy** [comment]
@kubukoz Yes, sure. I've just pushed it here https://github.com/disneystreaming/smithy4s/pull/1509
