### ISSUE TITLE
smithy4s-protocol not being written to smithy4sUpdateLSPConfig

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1517]
With a standard smithy4s setup, the `smithy-build.json` file looks like this:

```scala
{
    "version" : "1.0",
    "imports" : [
        "src/main/smithy",
        "target/scala-3.3.3/src_managed/main/smithy"
    ],
    "maven" : {
        "dependencies" : [
            "com.disneystreaming.alloy:alloy-core:0.3.6"
        ],
        "repositories" : [
        ]
    }
}
```

There's #1459, of course, but another problem is that `maven.dependencies` doesn't contain the artifact with traits form `smithy4s.meta` - namely `com.disneystreaming.smithy4s:smithy4s-protocol`.

I'm not sure if Alloy is special-cased in any way here, but if so, we should also special-case smithy4s-protocol. If it's not special-cased, something may be wrong in how we collect dependencies.

**Comment by kubukoz** [comment]
@daddykotex off the top of your head, do you have any hunch on why alloy is being written but smithy4s-protocol isn't?

**Comment by kubukoz** [comment]
looks like `alloy-core` is a `libraryDependencies` entry (`% Smithy4s`-scoped), but smithy4s-protocol isn't.

smithy4s-protocol is a dependency of the codegen / build plugin itself, being added to the model in `ModelLoader` via an explicit mention of the `smithy4s.meta.smithy` file:

https://github.com/disneystreaming/smithy4s/blob/7cc1aa9a1b34d30b90308eedd1edb7a7ddd7e1aa/modules/codegen/src/smithy4s/codegen/internals/ModelLoader.scala#L181-L187

unless we want to change how all that works, it'd probably be the easiest if we hardcode the protocol dependency in the smithy-build writing code

**Comment by daddykotex** [comment]
yes, I'm guessing it happens like that because the dependency comes in via `dependsOn` in the sbt project structure?

really not sure about that, and I can't remember more

**Comment by kubukoz** [comment]
I think we're gonna just want to hardcode the addition of this module (`com.disneystreaming.smithy4s:smithy4s-protocol`) in the LSP config codegen:

for starters, we could go with https://github.com/disneystreaming/smithy4s/blob/89e88c972174fa0a3b2853901a52a5a6a4662c6d/modules/codegen/src/smithy4s/codegen/SmithyBuildJson.scala#L34-L41, but maybe there's a better place.

**Comment by kubukoz** [comment]
Tests for this can be added in: https://github.com/disneystreaming/smithy4s/blob/89e88c972174fa0a3b2853901a52a5a6a4662c6d/modules/codegen/test/src/smithy4s/codegen/internals/SmithyBuildSpec.scala

The expectation is that you'll always have a Maven dependency written for `com.disneystreaming.smithy4s:smithy4s-protocol:${BuildInfo.version}` (where `BuildInfo` is `smithy4s.codegen.BuildInfo`).

As for manual testing, I suggest:

1. `sbt publishLocal_2_12_jvm`
2. setting up a sample smithy4s project with Scala 2.12
3. running `smithy4sUpdateLSPConfig`
4. Looking at the generated `smithy-build.json` in the project.
