### ISSUE TITLE
@default support for timestamps

### ISSUE THREAD

**Issue by msosnicki** [disneystreaming/smithy4s#1535]
Currently, the `@default` trait on `Timestamp` fields is not supported ([source](https://github.com/disneystreaming/smithy4s/blob/89e88c972174fa0a3b2853901a52a5a6a4662c6d/modules/codegen/src/smithy4s/codegen/internals/SmithyToIR.scala#L1420))

smithy supports setting the default value that depend on `@timestampFormat`, it would be nice if the codegen supported that too.

I can look into it if it's useful to have this feature

**Comment by Baccata** [comment]
> smithy supports setting the default value that depend on @timestampFormat, it would be nice if the codegen supported that too.

I'm not sure what you mean by that

**Comment by msosnicki** [comment]
```smithy

structure Foo {
        @required
        @timestampFormat("date-time")
        @default("2024-12-31T00:00:00Z")
        dateTime: Timestamp
}
```

is valid, but `@timestampFormat("epoch-seconds")` would require `@default(1000)`.

So what I meant, since it's validated on smithy level, it would be great if all `@timestampFormats` with defaults were supported

**Comment by Baccata** [comment]
I see. Then sure, feel free to PR it in. It shouldn't be too complicated, considering the default Document decoders are timestampFormat-aware. I think you'll just have to change code at the codegen level.

**Comment by msosnicki** [comment]
Ok, I will have a look into it
