### ISSUE TITLE
Chore: update sbt in the project and scripted tests

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1538]
In the `build.properties` scattered around the codebase, update sbt.version to whatever the latest stable version is (at time of writing, 1.10.0).

**Comment by Baccata** [comment]
I'd like it if we could sync the version of SBT used in scripted tests with what's actually used by the build. Any idea how we could do this ? It's not like we can use the usual "build-info" trick.

**Comment by kubukoz** [comment]
Can we modify the scripted task to first iterate over these directories and update if needed?

**Comment by Baccata** [comment]
possibly

**Comment by kubukoz** [comment]
I think we could also just delete `build.properties` in the test directories and it'll automatically use the "parent" sbt's version. That should be optimal.
