### ISSUE TITLE
Fix kebab-caseificiation 

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#1539]
See https://github.com/disneystreaming/smithy4s/blame/89e88c972174fa0a3b2853901a52a5a6a4662c6d/modules/decline/src/core/commons.scala#L31

Running this on a string that starts with a lowercase erases the first letter.

**Comment by plokhotnyuk** [comment]
@Baccata Could you please check if following functions pass your requirements then they will save a lot of CPU cycles in runtime: https://github.com/plokhotnyuk/jsoniter-scala/blob/ced2478473c992e99f783faedc132adcf55eed79/jsoniter-scala-macros/shared/src/main/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala#L484-L560

**Comment by Baccata** [comment]
@plokhotnyuk thanks :) tbh it's for a rather un-used CLI-derivation module, performances are not really that critical in this context, but I do appreciate the tip !

**Comment by dwalend** [comment]
I put in a PR - https://github.com/disneystreaming/smithy4s/pull/1603
