### ISSUE TITLE
Generated code should not be regenerated after switching Scala versions

### ISSUE THREAD

**Issue by bpholt** [disneystreaming/smithy4s#1589]
It appears to me that the code generator regenerates the code for a given Scala version after switching to another Scala version and then switching back. I've written a scripted test to demonstrate the problem, and I'll open a PR containing the test as a followup to this issue.

The motivation for why I think this is a problem is that I've written a [Scalafix](https://github.com/Dwolla/scala-secure-config/blob/3dc4677c70cf7c0b06e6f0981766ffbb269549c2/scalafix/rules/src/main/scala/com/dwolla/scalafix/smithy4s/PrivatizeGeneratedCode.scala#L13-L52) semantic rule that makes code generated by smithy4s package private, with the intent of being able to publish a smithy4s client as part of a library but avoid binary compatibility issues. The rule is idempotent so running it multiple times on the same files should have the same effect as running it once.

Semantic rules require that the code being modified have been compiled because the rule takes advantage of knowledge from the compiler. This means if the rule is modifying code in the `Compile` scope, and code in the `Test` scope depends on the modified code, you can't simply use `scalafixOnCompile := true` and then run `Test/compile` to compile them both at once. Instead, you must run `Compile/compile`, run the Scalafix rule (either explicitly or implicitly via `scalafixOnCompile`), and then run `Compile/compile` again. (The second `Compile/compile` can be triggered by sbt's task graph, so `Test/compile` would be fine the second time.)

I've written tests for [Scala 2](https://github.com/Dwolla/scala-secure-config/blob/3dc4677c70cf7c0b06e6f0981766ffbb269549c2/src/test/scala-2/bincompat/ShadedGeneratedSmithySpec.scala#L14) and [Scala 3](https://github.com/Dwolla/scala-secure-config/blob/3dc4677c70cf7c0b06e6f0981766ffbb269549c2/src/test/scala-3/bincompat/ShadedGeneratedSmithySpec.scala#L20) that demonstrate that the code-as-modified-by-Scalafix is inaccessible outside the library's package.

All of this seems to work as expected when the Scala version is selected, code is generated, Scalafix applied, modified code is compiled, and tests executed. i.e. 

```
clean
++ 2.13 // or ++ 3
compile // generate code and run Scalafix semantic rule, which requires the code to have been compiled
test    // compile the modified code and run tests
```

However, if the Scala version is changed after the Scalafix is applied, the code appears to be regenerated. This happens when, instead of using `++ 2.13` to switch the Scala version, you use e.g. `clean; +compile; +test`. Sbt will run `compile` for each of the cross Scala versions, and then start over and run `test` for each of the cross Scala versions.

In other words, if you're cross compiling `2.13.15` and `3.3.3`, `+compile; +test` will 
1. set the Scala version to `2.13.15`
2. run `compile` (which triggers smithy4s codegen, and then the Scalafix rule that modifies the generated code)
3. set the Scala version to `3.3.3`
4. run `compile` (which triggers smithy4s codegen, and then the Scalafix rule that modifies the generated code)
5. set the Scala version to `2.13.15`
6. run `test` (which _should_ just compile the modified generated code, but _actually_ regenerates and re-modifies the code, using the compiled but unmodified classes as the classpath when running the tests. if the tests don't compile or otherwise fail , sbt stops here)
7. set the Scala version to `3.3.3`
8. run `test` (same behavior as step 6)

FWIW, when looking at the build output in library I mentioned above, I can tell the difference between the initial Scalafix run and subsequent runs:
```
sbt:secure-config> ++ 2.13; compile; compile; compile
[info] Setting Scala version to 2.13.14 on 2 projects.
[info] compiling 30 Scala sources to target/scala-2.13/classes ...
[info] Running scalafix on 30 Scala sources
[success] Total time: 8 s, completed Sep 25, 2024, 5:12:16 PM
[info] compiling 30 Scala sources to target/scala-2.13/classes ...
[info] Running scalafix on 29 Scala sources (incremental)
[success] Total time: 3 s, completed Sep 25, 2024, 5:12:19 PM
[success] Total time: 0 s, completed Sep 25, 2024, 5:12:19 PM
```
vs
```
sbt:secure-config> +compile; +compile
[info] Setting Scala version to 2.13.14 on 2 projects.
[info] Excluded 1 projects, run ++ 2.13.14 -v for more details.
[info] Reapplying settings...
[info] compiling 30 Scala sources to target/scala-2.13/classes ...
[info] Running scalafix on 30 Scala sources
[success] Total time: 5 s, completed Sep 25, 2024, 5:15:06 PM
[info] Setting Scala version to 3.3.3 on 2 projects.
[info] Excluded 1 projects, run ++ 3.3.3 -v for more details.
[info] Reapplying settings...
[info] compiling 30 Scala sources to target/scala-3.3.3/classes ...
[info] Running scalafix on 30 Scala sources
[success] Total time: 13 s, completed Sep 25, 2024, 5:15:19 PM
[info] Reapplying settings...
[info] Setting Scala version to 2.13.14 on 2 projects.
[info] Excluded 1 projects, run ++ 2.13.14 -v for more details.
[info] Reapplying settings...
[info] Running scalafix on 30 Scala sources
[success] Total time: 3 s, completed Sep 25, 2024, 5:15:22 PM
[info] Setting Scala version to 3.3.3 on 2 projects.
[info] Excluded 1 projects, run ++ 3.3.3 -v for more details.
[info] Reapplying settings...
[info] Running scalafix on 30 Scala sources
[success] Total time: 3 s, completed Sep 25, 2024, 5:15:26 PM
```
Note that in the second case, it never says "scalafix on 29 Scala sources (incremental)"; it's always 30 sources. And in the first case, the third `compile` is a no-op, because the Scalafix didn't modify anything on its second run, so everything has already been compiled by the time the third `compile` executes.

Ultimately this all filters down to the artifact published by the project's build contains the unmodified generated code, so the generated code is not package private. See e.g. [`com.dwolla::secure-config:0.4-3dc4677-SNAPSHOT`](https://oss.sonatype.org/content/repositories/snapshots/com/dwolla/secure-config_3/0.4-3dc4677-SNAPSHOT/secure-config_3-0.4-3dc4677-SNAPSHOT.jar)

**Comment by Baccata** [comment]
Well, I kinda despise the `++` method of doing cross-compilation, as it essentially mutates build settings on the fly. Imho the [project-matrix](https://github.com/sbt/sbt-projectmatrix) way of doing things is a lot more principled, but I can empathise with the fact that it has some downsides (ie sbt-typelevel is not aware of it, and metals doesn't have a decent way of ignoring compilation targets, which implies suboptimal editor experience). 

Anyhow, I think to solve this, you'd have to ensure that the scala version is part of the [identifier of the cache](https://github.com/disneystreaming/smithy4s/blob/00f65317bbd583bc047f7f4d863df3176c2e766a/modules/codegen-plugin/src/smithy4s/codegen/Smithy4sCodegenPlugin.scala#L269). Intuitively, it should suffice, as mutating the settings to switch scala version would imply writing to a different cache file. 

Feel free to PR it in.

**Comment by bpholt** [comment]
Thanks @Baccata. I'll see what I can come up with!

**Comment by bpholt** [comment]
After pulling in `v0.18.25` (which includes the changes from #1590) and using it for a bit, I think this has been resolved.
