### ISSUE TITLE
Unnecessary imports generated

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#174]
In certain scenarios , imports are added to the generated service that are not needed.
This seems to be related to the packedinputs trait , as the imports would be needed for the unpacked version

**Comment by Baccata** [comment]
Indeed. I've been wanting to make that logic less brittle for a while. 

The rendering depends on an ad-hoc construct, called `RenderResult`, which contains both lines and imports. 

https://github.com/disneystreaming/smithy4s/blob/main/modules/codegen/src/smithy4s/codegen/Renderable.scala#L67

It works very well, but not so much when we try to compose things in a single line, as string interpolation is used. What I think we should do is create a single string interpolator, that would have knowledge of `RenderResult`, and would accumulate the imports behind the hood. 

This would make the logic of imports gathering a lot more precise, as it'd allow for more local reasoning.

**Comment by yisraelU** [comment]
@Baccata can we mark this closed?

**Comment by Baccata** [comment]
Sure
