### ISSUE TITLE
Try to make newtypes work better in Intellij

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#180]
IntelliJ (when not working in BSP mode) has trouble understanding that the `foo.Foo.T` type member is equal to the `foo.Foo` type alias. 

We **might** be able to make that better for the Intellij users, by overriding the `apply` method in the generated code. I'm not sure it'll work, as it might create an illegal cyclic reference at compile time.

**Comment by yisraelU** [comment]
@Baccata 
Using sbt and intellij 2022.3
I am not seeing any red squigglies when writing something like this
```
  val x: TypeAlias = TypeAlias("")
```

**Comment by kubukoz** [comment]
Not newtype related, but:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/894884/198417119-928fc5ca-b171-457c-8e67-f1c4ca6aec02.png">

Once you actually have a newtype it seems like it's fine:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/894884/198417521-d5160a2a-f91c-4407-85bc-84e293312160.png">

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/894884/198417582-9815b9c0-42ff-493c-a76e-6f5a97b38269.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/894884/198417612-1bffdaea-d309-4341-90e0-f2ebd82e94f5.png">

**Comment by Baccata** [comment]
Alright, I'll close this then (I'm concerned about end-user experience more than anything, end-users aren't likely to query hints and whatnot). 

Thanks folks :)
