### ISSUE TITLE
Setup a Scala Steward workflow

### ISSUE THREAD

**Issue by keynmol** [disneystreaming/smithy4s#252]
Frank Thomas' public instance of Steward will no longer be running (https://twitter.com/fst9000/status/1532088018084978689)

It's possible to achieve similar things by just dropping this cron-based workflow in the repo: https://github.com/scala-steward-org/scala-steward-action

Note that the same will need to be done for weaver-test and smithy4s.g8 (once that's operational)

**Comment by kubukoz** [comment]
I'd wait a couple days to see the results of https://contributors.scala-lang.org/t/can-scala-maintain-a-public-scala-steward-instance/5754.

**Comment by Baccata** [comment]
Not needed anymore
