### ISSUE TITLE
Operation error name conflict

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#255]
This Smithy spec generates code that doesn't compile:

```
namespace example

service A {
  operations: [MyOp]
}

operation MyOp {
  errors: [MyOpError]
}

@error("client")
structure MyOpError {}
```

Relevant code:

```scala
def unliftError(e: MyOpError) : Throwable = e match {
  case MyOpError.MyOpErrorCase(e) => e //here
}
```

Error:

```
type mismatch;
 found   : example.AGen.MyOpError
 required: Throwable
```

As I understand this is caused by a name conflict, in which `MyOpError` is both the name of the error trait *and* the name of the subtype wrapped by `MyOpErrorCase`.

**Comment by Baccata** [comment]
Maybe we could emit a `Danger` event in the smithy validator ?

**Comment by daddykotex** [comment]
In this case, isn't something that we can fix w/o requiring use input ?

the code:

**Comment by Baccata** [comment]
The problem is not the `e`, it's the fact that `MyOpError` (synthetised by smithy4s) is colliding with a user type and the compiler cannot distinguish them in this particular scope.

**Comment by daddykotex** [comment]
ahh I see

**Comment by kubukoz** [comment]
A fully qualified name would do it, but that's probably not what we want to do (ugly codegen)

**Comment by yisraelU** [comment]
#412 fixes this
