### ISSUE TITLE
Generate Scaladoc 

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#256]
Originally mentioned in https://github.com/disneystreaming/smithy4s/issues/245 : the `@deprecated` trait should generate a `@deprecated` annotation in the Scala code, and the `@documentation` / `@externalDocumentation` traits should result in some Scaladoc being generated.

**Comment by Baccata** [comment]
I wholefully agree with this

**Comment by kubukoz** [comment]
Started some work on the deprecations part of this.

**Comment by zetashift** [comment]
This looks like "fun" good-first-issue. If my noobie questions aren't too much hassle, I'll gladly pick this up.
https://github.com/disneystreaming/smithy4s/pull/599 should provide some tips on how to implement scaladoc in the codegen no?

I believe something like this:
- Add a case class`Documentation` which extends `Hint` to the IR
-  Then add a way to render scaladocs in `Renderer`

**Comment by daddykotex** [comment]
> This looks like "fun" good-first-issue. If my noobie questions aren't too much hassle, I'll gladly pick this up. #599 should provide some tips on how to implement scaladoc in the codegen no?
> 
> I believe something like this:
> 
> * Add a case class`Documentation` which extends `Hint` to the IR
> * Then add a way to render scaladocs in `Renderer`

I think you got that right! Good luck and don't hesitate to reach out here or on Discord if you need assistance

And thanks, really

**Comment by kubukoz** [comment]
yeah, I think you can draw some inspiration from #599. I left some hints for working on codegen code here, might be useful for a good feedback loop: https://github.com/disneystreaming/smithy4s/issues/496#issuecomment-1312563839

> I believe something like this:

that sounds about right

**Comment by kubukoz** [comment]
Mostly closed in #731, with some new tickets spawned to further improve this. Thanks @zetashift!
