### ISSUE TITLE
AWS: refreshing creds isn't leak safe

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#273]
```scala
def refreshLoop(ref: Ref[F, AwsTemporaryCredentials]): F[Unit] =
  for {
    lastCredentials <- ref.get
    now <- Clock[F].realTime.map(_.toSeconds)
    expires = lastCredentials.expiration.epochSecond
    delay = expires - now - 300
    _ <- Temporal[F].sleep(delay.seconds)
    newCredentials <- get
    _ <- ref.set(newCredentials)
    _ <- refreshLoop(ref)
  } yield ()
```

Although the `refreshLoop` recursive call is the last effect in the `for`, the forcomp is going to desugar to something like `....flatMap(_ => refreshLoop(ref).map(_ => ())`. That last `Map` node will end up on the heap forever, and with each run of the loop there will be one more.

The code should be updated, probably by using `>>` after the previous parts, or a manual `flatMap` call.

**Comment by kubukoz** [comment]
Similar issue: https://github.com/kailuowang/mau/issues/63

**Comment by daddykotex** [comment]
that's one hell of a trap

**Comment by kubukoz** [comment]
yeah, better-monadic-for made us lazy (it eliminates that final `map`) :)

**Comment by daddykotex** [comment]
how do you even realize that the final map will lead to a leak?

I guess you can only know if:

- you stumbled on it in practice, your app leaks and after investigating you find this is the culprit
- you know scala internals and the cats-effect runtime enough that it's something you can catch by reading the code

**Comment by Baccata** [comment]
Y U NO PR ? 😄

**Comment by kubukoz** [comment]
OSS 101: don't PR until maintainers acknowledge the issue ;)

**Comment by Baccata** [comment]
I acknowledge. Now where's my PR ?

**Comment by kubukoz** [comment]
Those demanding OSS maintainers these days...
