### ISSUE TITLE
Ensure headers referenced in smithy specs are actually settable

### ISSUE THREAD

**Issue by littlenag** [disneystreaming/smithy4s#28]
We have an API where we have required that the "content-type" header be set as part of the smithy spec, eg

    @required
    @httpHeader("content-type")
    contentType: CustomContentType

Unfortunately due to how http4s works, if you derive a client for this API, the trait will require the parameter, but the actual request generated will have the "static" header value ie "Content-Type: application/json; charset=UTF-8". 

Smithy4s should disallow headers that it knows it cannot reliably set.

**Comment by Baccata** [comment]
To be clear, what's preventing this to work is https://github.com/http4s/http4s/issues/146. We could obviously hack something and post-process it, but I'm not keen on adding such a hack. 

As a workaround, this can be implemented as http4s client middleware (ie, a `Client[F] => Client[F])` function
