### ISSUE TITLE
Service with no operations gen

### ISSUE THREAD

**Issue by lewisjkl** [disneystreaming/smithy4s#3]
When a service has no operations in it, the generated code has a compilation error. For example:

```smithy
namespace test

use smithy4s.api#simpleRestJson

@simpleRestJson
service MyService {
  version: "1",
  operations: []
}
```

would generate:

```scala
sealed trait MyServiceOperation[Input, Err, Output, StreamedInput, StreamedOutput]

def asTransformationGen[P[_, _, _, _, _]](impl : MyServiceGen[P]): smithy4s.Transformation[MyServiceOperation, P] = new smithy4s.Transformation[MyServiceOperation, P] {
    def apply[I, E, O, SI, SO](op : MyServiceOperation[I, E, O, SI, SO]) : P[I, E, O, SI, SO] = op match  { // error empty match
    }
  }

def endpoint[I, E, O, SI, SO](op : MyServiceOperation[I, E, O, SI, SO]) = op match { // error empty match
  }
```

Of course, why would one want to generate code for a service with no operations? They probably wouldn't.. but maybe I am not thinking of other use cases.
 
I am thinking we should make it so that we automatically do not generate any code for services with no operations.

For those wondering why one would even have a service with no operations in the first place, it can be helpful for if you have a prior version of a service that you want to represent/annotate with traits in smithy without documenting it fully.

**Comment by kubukoz** [comment]
Sounds like this could be a validator.

**Comment by lewisjkl** [comment]
> Sounds like this could be a validator.

You mean a validator that will prevent services from having an empty list of operations?

**Comment by kubukoz** [comment]
Yeah, seems useless :) it should be part of the default smithy validators, really (just like you can't have an enum without values)

**Comment by Baccata** [comment]
Actually internally we have a use-case for empty services. 

In any case, it's gonna be an easy fix. I'll get it before 0.9.1
