### ISSUE TITLE
schematic.StubSchematic can't be used in Scala.JS

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#34]
It breaks linking because of extending `javatime.StubSchematic`:

```scala
object CompletionSchematic {
  type Result[A] = List[String]
}

class CompletionSchematic extends smithy4s.StubSchematic[CompletionSchematic.Result] {
  def default[A]: List[String] = Nil
}
```

```
[error] Referring to non-existent method schematic.javatime$StubSchematic.$init$()void
[error]   called from constructor playground.CompletionSchematic.<init>()void
[error]   called from private playground.completions$.$anonfun$complete$10(scala.collection.immutable.List,smithy4s.Service,playground.smithyql.Query,playground.smithyql.WithSource$Thing)scala.collection.IterableOnce
[error]   called from private playground.completions$.$anonfun$complete$9(scala.collection.immutable.List,smithy4s.Service,typings.vscode.mod.TextDocument,typings.vscode.mod.Position)scala.collection.immutable.List
[error]   called from playground.completions$.complete(smithy4s.Service)scala.Function2
[error]   called from playground.extension$.activate(typings.vscode.mod.ExtensionContext)void
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   playground.completions$
[error]   playground.extension$
[error] There were linking errors
[error] (vscodeJS / Compile / fastLinkJS) There were linking errors
```

**Comment by lewisjkl** [comment]
I was taking a look at this earlier and I think I might be missing something. I created a javascript test with the contents:

```scala
package schematic

object JavatimeSpec extends weaver.FunSuite {

  object CompletionSchematic {
    type Result[A] = List[String]
  }

  class CompletionSchematic extends StubSchematic[CompletionSchematic.Result] {

    override def genericStruct[S](
        fields: Vector[Field[CompletionSchematic.Result, S, _]]
    )(const: Vector[Any] => S): CompletionSchematic.Result[S] = ???

    def default[A]: List[String] = Nil
  }

  test("testing") {
    val cs = new CompletionSchematic()
    expect(cs.default == Nil)
  }

}
```
which seems to work without any compilation issues.

The current js implementation of javatime looks like:

```scala
package schematic

object javatime {

  trait Syntax

  type Schematic[F[_]] = Any

  object Schematic {
    trait Mixin[F[_]]
  }

  trait StubSchematic[F[_]] extends Schematic.Mixin[F] {}

}
```

Anyway, more context here would be appreciated so I can reproduce this on my end

**Comment by kubukoz** [comment]
Does that test run? I can compile all right, but `fastLinkJS` gives me the same thing as before.

**Comment by kubukoz** [comment]
https://github.com/kubukoz/schematic-repro

I think I see what's wrong, the codegen plugin is pulling in core via `%%`. For some reason that isn't a problem for anything else that I've been using...

Anyway, removing the plugin-added dependency and using my own one seems to fix it, but I think this should be fixed in the plugin itself...

**Comment by lewisjkl** [comment]
Ah good catch, I will update that tomorrow

**Comment by kubukoz** [comment]
I wonder if there's a way to have `%%%` without forcing the Scala.JS plugin to be added to downstream builds...

**Comment by lewisjkl** [comment]
Yeah I don't think there is a way to do it. I chatted with @Baccata earlier and it seems like removing the core dependency from the plugin is probably the best path forward.

I guess we could go the route of having a setting that can be overridden to prevent the core dependency from loading, but it seems like that sort of thing would cause more confusion than it would save since anyone using scala JS would have to be magically aware of it. Open to other ideas here though
