### ISSUE TITLE
Default timestamp format inconsistency between OpenAPI and json codec

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#43]
The default timestamp format in `SchematicJCodec` [defaults to `DATE_TIME`](https://github.com/disneystreaming/smithy4s/blob/38d51ec3764aa9964b018e14cf4f9152fa793aac/modules/json/src/smithy4s/http/json/SchematicJCodec.scala#L290), but the OpenAPI generator [defaults to EPOCH_SECONDS](https://github.com/disneystreaming/smithy4s/blob/38d51ec3764aa9964b018e14cf4f9152fa793aac/modules/openapi/src/smithy4s/openapi/Smithy4sOpenApiProtocol.scala).

We should pick one (preferably DATE_TIME) and use it consistently within the protocol - I'm not sure if it can be configured in `smithy4s.smithy` or it just needs to be codified (the spec isn't [entirely clear](https://awslabs.github.io/smithy/1.0/spec/core/protocol-traits.html#timestampformat-trait) on what "implicit format" means).

**Comment by Baccata** [comment]
See https://awslabs.github.io/smithy/1.0/spec/aws/index.html#aws-protocols for an example of what is meant by "implicit format"
