### ISSUE TITLE
Mixins are not inherited in Dynamic Model

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#453]
Issue : https://github.com/disneystreaming/smithy4s/blob/b257e4cbfab5d46b9484fa8682a6619776e1eb93/modules/dynamic/src-jvm/DynamicSchemaIndexPlatform.scala#L31

Summary: 
When using the software.amazon.smithy.model.shapes.ModelSerializer from AWS , any members added in ( aka inherited) via a Mixin will be removed from members object and stored in a separate json object for Mixins. This makes the ModelSerializer a bad candidate for piping information to the Dynamic model, as it currently stands Mixins will not be included in the Dynamic model
See the Serialized Model below ,  MyStruct does not contain a member MyInt

```

    "smithy": "2.0",
    "shapes": {
        "test#MyInt": {
            "type": "structure",
            "members": {
                "theInt": {
                    "target": "smithy.api#Integer"
                }
            },
            "traits": {
                "smithy.api#mixin": {}
            }
        },
        "test#MyStruct": {
            "type": "structure",
            "mixins": [
                {
                    "target": "test#MyInt"
                }
            ],
            "members": {
                "str": {
                    "target": "smithy.api#String"
                }
            }
        }
    }
}
```

**Comment by kubukoz** [comment]
The serialized model for:

```
$version: "2"
namespace test

@mixin
structure HasData {
  @required
  data: String
}

structure Data with [HasData] {
  @required
  id: Integer
}
```

looks like this:

```json
{
    "smithy": "2.0",
    "shapes": {
        "test#Data": {
            "type": "structure",
            "mixins": [
                {
                    "target": "test#HasData"
                }
            ],
            "members": {
                "id": {
                    "target": "smithy.api#Integer",
                    "traits": {
                        "smithy.api#required": {}
                    }
                }
            }
        },
        "test#HasData": {
            "type": "structure",
            "members": {
                "data": {
                    "target": "smithy.api#String",
                    "traits": {
                        "smithy.api#required": {}
                    }
                }
            },
            "traits": {
                "smithy.api#mixin": {}
            }
        }
    }
}
```

so the dynamic model _does_ contain the mixins, they're just not inlined. This is not aligned with the fact that `smithy4s.dynamic.model.Model`'s schema expects the members to... be there - it doesn't include the `mixins` field.

For example, if we try to decode a dynamic model like the above, and look up the fields in `test#Data`:

```scala
println(
  DynamicSchemaIndex
    .loadModel(model)
    .toTry
    .get
    .getSchema(ShapeId("test", "Data"))
    .get
    .asInstanceOf[Schema.StructSchema[_]]
    .fields
    .map(_.label)
)
```

It only shows `id`.

[Repro](https://github.com/kubukoz/demos/tree/smithy4s-dynamic-missing-mixins)

**Comment by yisraelU** [comment]
@kubukoz updated my initial statement.
essentially moving off the Model Serializer will solve the problem as  the Model itself has the mixins appropriately inherited

**Comment by yisraelU** [comment]
@kubukoz Lets convert this to a ticket to add Mixins to the Dynamic Model

**Comment by kubukoz** [comment]
I thought @Baccata wanted it to be done without changes in the dynamic model
