### ISSUE TITLE
Codegen forces upstream module compilation

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#484]
In a project like this:

```scala
val core = project

val root = project
  .in(file("."))
  .dependsOn(core)
  .enablePlugins(Smithy4sCodegenPlugin)
```

Running `smithy4sCodegen` on root level triggers compilation of `core`. You can prove this by putting non-compiling Scala code in `core`, in which case `smithy4sCodegen` will fail. No smithy files necessary. `.dependsOn(core % "compile->compile")` doesn't change this.

Can't reproduce this in 0.15.3. My guess is that this is caused by https://github.com/disneystreaming/smithy4s/pull/432/ and might be a deliberate change in behavior (but it's not documented as such).

[Reproduction repo](https://github.com/kubukoz/demos/tree/smithy4s-compilation-trigger)

**Comment by kubukoz** [comment]
Okay, looks like it is indeed #432 - it introduces a dependency on `Compile / internalDependencyAsJars` which... makes sense. Is there any way we could get away without doing the actual compile, though?

**Comment by Baccata** [comment]
I wouldn't opposed a PR that would result in skipping any module that doesn't have the `smithy4sSmithyLibrary` setting set, during the gather of upstream jars. Not gonna lie : SBT does not make this kind of logic really easy.
