### ISSUE TITLE
Mill plugin : "default" config causes infinite compile / run loop with -w flag

### ISSUE THREAD

**Issue by Quafadas** [disneystreaming/smithy4s#488]
This project is a horridly broken work in progress, but 
https://github.com/Quafadas/mill-full-stack/blob/master/build.sc

`./mill -w -d shared.compile`

Will send mill into a tailspin, where it seems to be constantly re-triggering it's own compilation. 
```
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] No changes
Watching for changes to 9 paths... (Enter to re-run, Ctrl-C to exit)
Using explicit system properties: Map()
[68/93] backend.resources 
Watching for changes to 9 paths... (Enter to re-run, Ctrl-C to exit)
Using explicit system properties: Map()
[68/93] backend.resources 
Watching for changes to 9 paths... (Enter to re-run, Ctrl-C to exit)
Using explicit system properties: Map()
[68/93] backend.resources 
Watching for changes to 9 paths... (Enter to re-run, Ctrl-C to exit)
Using explicit system properties: Map()
[68/93] backend.resources 
Watching for changes to 9 paths... (Enter to re-run, Ctrl-C to exit)
```

I think this command
```
./mill showNamed shared.allSources
```
Provides some notion of what's happening, although don't pretend to fully understand. 

I'm not clear if this is something I should be trying to fix in configuration - I could pipe the compiled output somewhere else for example, as per the docs, or whether this is an issue with the plugin itself?

**Comment by kubukoz** [comment]
Hi @Quafadas, are you able to simplify the project into something that reproduces this behavior without redundant context? (e.g. laminar)

Ideally it'd also be a permalink, so that changes to your master branch wouldn't affect the code linked. You can get a permalink for a file/folder on github by pressing `y`, btw

**Comment by Quafadas** [comment]
Yes, apologies. 

https://github.com/Quafadas/mill-full-stack/blob/32c696ecb3295e550828991c3bd0c1d406c9b77e/build.sc#L28
```
git clone https://github.com/Quafadas/mill-full-stack.git
git checkout tailspin
./mill -w shared.compile
```
As far as I can tell, there's no other cruft remaining on the "tailspin" branch, and I get the repeat compile behaviour... 

https://user-images.githubusercontent.com/24899792/194122773-0bde90e0-48ae-4fa6-aa4e-0e93152cbb98.mov

**Comment by daddykotex** [comment]
With `visualizePlan`, I can see the following:

![out](https://user-images.githubusercontent.com/5230460/195147744-5e94d03c-410f-4461-ba41-ae07b73f3566.png)

Which I guess shows what's wrong...
I'm looking into it, so far, I can't figure out why that's happening but still
