### ISSUE TITLE
Local jar dependency between Compile and Test causes redundant codegen

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#500]
```scala
val root = project
  .in(file("."))
  .enablePlugins(Smithy4sCodegenPlugin)
  .settings(
    scalaVersion := "2.13.8",
    libraryDependencies ++= Seq(
      "com.disneystreaming.smithy4s" %% "smithy4s-core" % smithy4sVersion.value
    ),
    Smithy4sCodegenPlugin.defaultSettings(Test)
  )
```

In a setup like this, running `Test/smithy4sCodegen` seems to have zero caching - it'll re-run the actual action every time you call it. It's easier to showcase with a large model, such as an AWS spec: [here's a repro with AWS Lambda](https://github.com/kubukoz/demos/tree/smithy4s-local-config-dependency).

I checked and the last version that didn't have this issue was 0.15.3. In my experience, to surface this issue you need to have both Smithy sources in `main/smithy`, but you don't need Scala sources.

`Test / smithy4sLocalJars := Nil` is a workaround, but it's not going to be a viable one if you _do_ want the `Compile` sources to be used.

I checked and this doesn't seem to happen with multiple modules (I don't think we have scripted tests for it, but it'd be nice to - not sure how we could check that a task used the cache, though) - just between configurations.

**Comment by Baccata** [comment]
I am definitely encountering a similar issue in the Smithy4s repo, and haven't spent the time to investigate the why. Thanks for opening this.
