### ISSUE TITLE
AWS: putting specs in a local jar dependency makes validation fail downstream

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#504]
Consider this build:

```scala
Global / onChangedBuildSource := ReloadOnSourceChanges

val core = project
  .enablePlugins(Smithy4sCodegenPlugin)
  .settings(
    scalaVersion := "2.13.8",
    libraryDependencies ++= Seq(
      "com.disneystreaming.smithy4s" %% "smithy4s-aws" % smithy4sVersion.value
    )
  )

val root = project
  .in(file("."))
  .enablePlugins(Smithy4sCodegenPlugin)
  .settings(
    scalaVersion := "2.13.8"
  )
  .dependsOn(core)
```

If you put one AWS spec, say `kinesis.json` into `core`, `core/compile` will succeed but `root/compile` will fail at the `smithy4sCodegen` step:

```
sbt:root> compile
[error] stack trace is suppressed; run last Compile / smithy4sCodegen for the full output
[error] (Compile / smithy4sCodegen) software.amazon.smithy.model.validation.ValidatedResultException: Result contained ERROR severity validation events: 
[error] [ERROR] com.amazonaws.lambda#Lambda1: Unable to resolve trait `aws.protocols#restJson1`. If this is a custom trait, then it must be defined before it can be used in a model. | Model jar:file:/Users/kubukoz/projects/demos/core/target/scala-2.13/core_2.13-0.1.0-SNAPSHOT.jar!/META-INF/smithy/kinesis.json:7:36
[error] Total time: 0 s, completed Oct 9, 2022, 4:44:10 PM
```

Extra info:

- This also happens if you split the dependencies between `Compile` and `Test` of a single module.
- It doesn't happen if `core` is a remote dependency (tested with `core/publishLocal` and replacing `dependsOn` with a `libraryDependencies` entry)
- As I understand, the definitions that aren't being found are runtime dependencies of the sbt plugin, and should be seen by the validators.
- It works in 0.15.3, doesn't work in either 0.16.1, 0.16.2, 0.16.3 or a snapshot from 1fdb46b105cddb8f48609a4f695e505bddf5e3b9

~~I'll open a PR with a scripted test for this soon.~~ #505

Workaround: add to `root`:

```scala
libraryDependencies ++= Seq(
  "software.amazon.smithy" % "smithy-aws-traits" % smithy4s.codegen.BuildInfo.smithyVersion % Smithy4s
)
```

**Comment by kubukoz** [comment]
in case I get hit by a truck before I make the PR: this is enough to trigger this issue.

```json
{
  "smithy": "1.0",
  "shapes": {
    "com.amazonaws.lambda#Lambda1": {
      "type": "service",
      "traits": {
        "aws.protocols#restJson1": {}
      }
    }
  }
}
```

**Comment by kubukoz** [comment]
In general I feel like this is going to be similar to https://github.com/disneystreaming/smithy4s/pull/462 somehow...

**Comment by kubukoz** [comment]
mayyyyyybe `"software.amazon.smithy" % "smithy-aws-traits" % smithy4s.codegen.BuildInfo.smithyVersion % Smithy4s` should be a dependency of `smithy4s-aws`?

**Comment by Baccata** [comment]
> mayyyyyybe "software.amazon.smithy" % "smithy-aws-traits" % smithy4s.codegen.BuildInfo.smithyVersion % Smithy4s should be a dependency of smithy4s-aws?

I think it'd certainly be a better design overall, but depending on `smithy4s-aws` would not pull `smithy-aws-traits % ... % Smithy4s` transitively. We'd probably have to bake it somehow in the pom file of `smithy4s-aws`, and amend the SBT plugin with some reasonably complex logic to add the corresponding data.

In all frankness I'm actually confused as to how `core` passes validation.

**Comment by kubukoz** [comment]
> In all frankness I'm actually confused as to how `core` passes validation.

For `core`, `.addClasspathModels(currentClassLoader, discoverModels)` is called and `discoverModels` is always true in the sbt plugin

**Comment by kubukoz** [comment]
> We'd probably have to bake it somehow in the pom file

I think I have yet another usecase for this internally which would make this really really nice to have.

**Comment by kubukoz** [comment]
Closed in #573 (is it me or did github stop understanding "closes X" in PR descriptions?)

**Comment by lewisjkl** [comment]
> Closed in https://github.com/disneystreaming/smithy4s/pull/573 (is it me or did github stop understanding "closes X" in PR descriptions?)

I've observed the same.. I figured it was something to do with repo permissions? Idk though

**Comment by kubukoz** [comment]
ok I think I get it: you have to target the default branch. Issues won't be closed if you're not merging into main.
