### ISSUE TITLE
Add a "Hint Mask" construct 

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#52]
We use the same Schematic implementation in various protocols/usecases. One problem is some protocols might not be aware of some hints. For instance, AWS' RestJson is unaware of discriminated unions. We should be able to pass hint masks to Schematic implementations, that would be used in the `withHints` method, preventing the discovery (and associated behaviour) of irrelevant hints.

**Comment by kubukoz** [comment]
Implemented in #70
