### ISSUE TITLE
Upgrading GH actions

### ISSUE THREAD

**Issue by daddykotex** [disneystreaming/smithy4s#523]
When looking at the workflows, we see warnings about deprecated usage of node12 in some of our GitHub actions.

![Screen Shot 2022-10-17 at 15 08 20](https://user-images.githubusercontent.com/5230460/196262132-fe1f153e-fc57-4e6e-a562-a4dfbea3379e.png)

**Comment by Baccata** [comment]
Yeah happy to upgrade.
