### ISSUE TITLE
Add a `projector` method to `Alt.Dispatcher`

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#530]
Add a `projector` method to `Alt.Dispatcher` that takes an `Alt[F, U, A]` and returns a `U => Option[A]`

```scala
def projector[F[_], A](alt: Alt[F, U, A]) : U => Option[A] 
```

This will prove useful for some schema compilers that rely on the presence of prisms.

**Comment by kubukoz** [comment]
Closed in #582
