### ISSUE TITLE
Big json arrays?

### ISSUE THREAD

**Issue by Quafadas** [disneystreaming/smithy4s#531]
It would appear that a smithy client which requests a large JSON array, is presented with this response. 

```
PayloadError(.data, expected = list, message=Input list exceeded max arity of 1024)
```
According to a DM with @Baccata , the most likely reason, is that the parser is intentionally set, to limit the parsing of large arrays for security reasons. 

Proposed Outcome:  Offer a mechansim via which the client would attempt to parse this unreasonably large array. Perhaps by offering a "turn off the security" flag?

**Comment by yisraelU** [comment]
@Quafadas can you pull latest version and verify that the new feature allowing passing in max arity solves your problem
