### ISSUE TITLE
Derive tests from test-traits

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#54]
AWS has a set of traits that they use to derive tests for their HTTP protocols. For instance, [here](https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/restJson1/documents.smithy). 

Without any code generation, we should be able to provide some weaver-specific interpreters, that'd essentially create a test suite based on these traits (both for servers and clients). 

This would be insanely valuable, as we'd be able to test our tooling against the AWS suites, or offer suites of our own so that people can test their own tooling against us (which may not necessarily be JVM centric, nor Scala centric)

**Comment by daddykotex** [comment]
some part happened here: https://github.com/disneystreaming/smithy4s/pull/424
Subsequent part happening here: https://github.com/disneystreaming/smithy4s/pull/527

**Comment by Baccata** [comment]
This is effectively done, in that we can now use the test traits in smithy and get corresponding tests in Scala code (reasonably) painlessly
