### ISSUE TITLE
Feature idea: strict document decoder

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#547]
Given a schema like `structure A { s: String }`, it would fail decoding a value like `{ y: "foo" }`.

Usecase: Dynamic land.

**Comment by Baccata** [comment]
I'm not sure that's something valuable enough to host in the library. Strict decoders are problematic whenever API evolve, I personally see them as little value. The maintenance-cost / value ratio is therefore too low for me to entertain this idea. 

Moreover, it'd be easy enough to implement in userland, at the cost of a little bit of copy/paste.
