### ISSUE TITLE
`unsafeCacheBy`: make public?

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#590]
In 0.17, it seems like `precompute` has been renamed to `unsafeCacheBy` and made `private[smithy4s]`. Could this be made public again?

**Comment by kubukoz** [comment]
I have a stake in this for Playground: https://github.com/kubukoz/smithy-playground/blob/984552c3b3293ae839386ae8fc03fb51c2c5333f/modules/core/src/main/scala/playground/DynamicServiceProxy.scala

and I know of one usecase inside DS for precomputing transformations :)

**Comment by Baccata** [comment]
I don't really want to revert it to public cause this memoization is a big footgun that leads to memory leaks when not applied carefully.

**Comment by kubukoz** [comment]
fine
