### ISSUE TITLE
JSON decoding throws on top-level struct fields missing

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#594]
For the following model:

```smithy
namespace hello

structure Event {
    @required
    payload: Payload
}

structure Payload {
    @required
    id: String
}
```

This code throws:

```scala
import hello._

object Main extends App {
  val capi =
    smithy4s.http.json.codecs.apply(smithy4s.http.json.codecs.defaultHintMask)

  val codec =
    capi.compileCodec(
      Event.schema
    )

  println {
    // this is an Either[PayloadError, Event]
    capi.decodeFromByteArray(
      codec,
      """{}""".getBytes
    )
  }
}
```

Exception:

```
PayloadError(.payload, expected = payload, message=Missing required field)
```

Notes:

- This happens in 0.16.7, 0.15.2 and even 0.12.0, so I think it's always been like that.
- if you try to decode `{"payload": {}}`, you get a `Left` as expected
- Unions don't seem to be affected

**Comment by plokhotnyuk** [comment]
I bet that `@required` is for checking existence a whole JSON key/values pair.

My expectation that `{"payload":{"id":"XXX"}}` should be parsed, and all following inputs should throw `Missing required field` errors:
`{"payload":{"id":null}}`
`{"payload":null}`
`{"payload":{}}`
`{}`

**Comment by kubukoz** [comment]
Managed to minimize it all to:

```
structure Event {
    @required
    payload: String
}
```

Sending a `{"payload": null}` results in a Left.

**Comment by kubukoz** [comment]
My understanding is that in:

https://github.com/disneystreaming/smithy4s/blob/ef44cdef5809022130923e1ce8e48396a10dbc3f/modules/json/src/smithy4s/http/json/JsonCodecAPI.scala#L59-L72

we're only catching the error in the partial decoding, and not the error in the full decoding. `readFromByteBuffer` returns a `Map[String, Any] => A` which throws the exception we see here.

question is... is it actually the problem, or just a symptom of `readFromByteBuffer` not throwing?

**Comment by plokhotnyuk** [comment]
Yes, I mean that the library method should throws the error that should be caught by the user on the level where it should be handled.

Moreover, wrapping output by `Either` is a kind of overhead anti-pattern in the age of cats-effect and ZIO.

**Comment by kubukoz** [comment]
> Moreover, wrapping output by Either is a kind of overhead anti-pattern in the age of cats-effect and ZIO.

That would be a separate story ;) we could probably optimize our usage by catching into IO directly, but that would require API changes.

With the issue at hand, I had a quick look at how structs are decoded and I think I know the answer to:

> question is... is it actually the problem, or just a symptom of readFromByteBuffer not throwing?

It would be the former - the partial decoding finds an empty Map (no interesting fields found) and the `.complete(MMap.empty)` step in `CodecAPI`'s implementation of `decodeFromByteArray` throws.

A short-term solution would probably be to catch it there, but long-term maybe we should consider changing the signature of `complete` to account for possible failures. This would be in conflict with the above suggestion to get rid of Eithers in CodecAPI.
