### ISSUE TITLE
Hints on collection members aren't generated

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#600]
Spawned by https://github.com/disneystreaming/smithy4s/pull/599#discussion_r1020671261.

You can apply some hints on collection members, e.g.:

```smithy
list Strings {
  @deprecated @documentation("foo") member: String
}
```

and they don't end up in the generated schema. This should be fixed, so that the collection's schema includes the hints.

Also: check if the dynamic model reads these hints.

**Comment by kubukoz** [comment]
bruh I'm literally tripping, I just made https://github.com/disneystreaming/smithy4s/issues/609 which is the exact same thing

**Comment by Baccata** [comment]
Did you mean enum members instead of collection members ?

**Comment by kubukoz** [comment]
enum members are done in #599. I meant collection indeed
