### ISSUE TITLE
AWS: expose list of supported protocols

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#601]
This is pretty much a nice-to-have, but anyway...

In smithy-playground, I currently maintain a list of supported AWS protocols. When another one is added in smithy4s, I'll get support for it "for free", but I'll need to remember to update [that list](https://github.com/kubukoz/smithy-playground/blob/984552c3b3293ae839386ae8fc03fb51c2c5333f/modules/core/src/main/scala/playground/OperationRunner.scala#L228-L229).

It would be cool if `AwsClient.prepare` failed with a list of known protocols (in case the service doesn't have either of them), or if there was a public list of them exposed in a val somewhere. It's also fine if this doesn't happen, it's not like we change the list of protocols every week.

**Comment by Baccata** [comment]
Yeah that'd be fine. 

Full disclosure : I think the AWS modules should move to another repo, as we stabilise the API of the core module.

**Comment by kubukoz** [comment]
closed in #619
