### ISSUE TITLE
Codegen - Package object definitions seem to be overwritten

### ISSUE THREAD

**Issue by simonsouter** [disneystreaming/smithy4s#616]
Code generation appears to put simple types defined in smithy files in a package object.  But if more than one smithy file in the same package contains simple types, it seems like the generated package object source file is overwritten as only types from one of the smithy files is generated.

Example

```
//file a.smithy
package smithy.test
string Test123

//file b.smithy
package smithy.test
string Test234

```
Resulting package object only has 'type Test234'.  Test123 does not appear in the generated source at all.

**Comment by kubukoz** [comment]
Hi :) I tried this with a different namespace (`smithy.test` seems to hit some sort of special handling based on the `smithy` prefix and doesn't generate any Scala files):

```smithy
namespace my.test

string Test123

```

```smithy
namespace my.test

string Test234
```

and I'm getting this package object:

```smithy
package object test {

  type Test234 = my.test.Test234.Type
  type Test123 = my.test.Test123.Type

}
```

so I'm not able to reproduce it (with sbt or the CLI) - can you provide more details?

**Comment by simonsouter** [comment]
Thanks for checking.  Figured out issue is caused by proprietary schema registry stuff, not smith4s.
