### ISSUE TITLE
Try to make `Endpoint[Op, HEYYEYAAEYAAAEYAEYAA]` just an `Endpoint[Op]`

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#620]
Just adding this one so that I don't forget to try and implement that. The params would be type members, and I think with the Aux pattern we could make it work with transformations.

**Comment by kubukoz** [comment]
@Baccata when you have a sec

**Comment by Baccata** [comment]
Generally speaking, I don't think those are questions that cannot be answered before experiementation. You need to try it out and see how much you can simplify the types at hand and still get a sound paradigm out of them. 

> Should it stay the same or would we set all the type members inside the object? The problem with this shape is that Scala complains about extending a non-class type: 

I think the type members can go in the object. In theory static objects are "transparent" wrt their type members, so I think it wouldn't break much.

**Comment by Baccata** [comment]
I've given it a quick go and I'm starting to think it's not worth the added complexity of trying to have the compiler reconcile type members with type parameters

**Comment by kubukoz** [comment]
yeah, I think that checks out. Let's scrap it
