### ISSUE TITLE
Model resources in dynamic module + handle them the same way codegen does 

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#687]
See https://github.com/disneystreaming/smithy4s/pull/686

When a service reference a resource, the operations of the resource (and all its sub-resources) should be added to the dynamic service. 

This implies that resources should be fully modelled in our dynamic model.

**Comment by msosnicki** [comment]
I can have a look into it.

**Comment by Baccata** [comment]
That'd be great :)
