### ISSUE TITLE
Enable incremental compilation

### ISSUE THREAD

**Issue by igor-ramazanov** [disneystreaming/smithy4s#688]
The sbt plugin seems to regenerate the code all the time, causing a vast recompilation.
E.g.:
```scala
import cats.effect.*
import com.amazonaws.ec2.*
import epollcat.EpollApp
import org.http4s.ember.client.EmberClientBuilder
import smithy4s.aws.*
import smithy4s.aws.http4s.*

object Main extends EpollApp.Simple:
  def run: IO[Unit] =
    EmberClientBuilder
      .default[IO]
      .build
      .flatMap(client => EC2.awsClient(client, AwsRegion.EU_NORTH_1))
      .use(ec2 => ec2.describeImages().run)
      .flatMap(IO.println)
      .void
```
triggers recompilation of 2925 classes on each change.

**Comment by Baccata** [comment]
@igor-ramazanov it shouldn't be the case. Could you share your build by any chance so that we can see whether we can reproduce ?

**Comment by Baccata** [comment]
Here's the caching mechanism in the SBT plugin : https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/codegen-plugin/src/smithy4s/codegen/Smithy4sCodegenPlugin.scala#L290

**Comment by kubukoz** [comment]
@igor-ramazanov does this happen in scala(jvm) or just native?

**Comment by igor-ramazanov** [comment]
@kubukoz Hey, tested on macOS and caching works without any issues both for JVM and Native.

For some reason, I've faced full recompilation on Linux, will check it out in more details tomorrow.

**Comment by igor-ramazanov** [comment]
Ok, my apologies, re-verified it on Linux and incremental compilation works without issues, thanks :)
