### ISSUE TITLE
Decoding an optional field fails when receiving a Document.DNull 

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#697]
I noticed that the DocumentDecoderSchemaVisitor will produce a decoder that always fails on DNull,
As null is both a valid json value and smithy value, shouldnt this be handled ?

**Comment by kubukoz** [comment]
I think so, yeah.

**Comment by yisraelU** [comment]
@Baccata thoughts?

**Comment by Baccata** [comment]
Well it depends on what you're trying to decode really, but I'm gonna need a repro, cause looking at the code I'm not totally convinced it always fail on `DNull`

**Comment by Baccata** [comment]
So this works : 

``` 
//> using lib "com.disneystreaming.smithy4s::smithy4s-core:0.17.1"
import smithy4s._

object Main {

  def main(args: Array[String]): Unit = {
    println(Document.Decoder.fromSchema(Schema.document).decode(Document.DNull)) // returns Right(Document.DNull)
  }
}
```

which means that the issue is bound to some context which is yet to be disclosed.

**Comment by yisraelU** [comment]
that makes sense that it works because the schema wants a DNull, I sm refering to where its expecting a String or Integer etc.. and it receives a DNull
i.e.  this fails
```
  val doc = smithy4s.Document.obj("a" -> smithy4s.Document.nullDoc)
case class NullExample(a: String)
object NullExample extends ShapeTag.Companion[NullExample] {
  val id: ShapeId = ShapeId("awstests", "NullAndEmptyHeadersIO")

  val hints : Hints = Hints.empty

  implicit val schema: Schema[NullExample] = struct(
    string.required[NullExample]("a", _.a)
  ){
    NullExample.apply
  }.withId(id).addHints(hints)
}
```

**Comment by Baccata** [comment]
@yisraelU then no, it doesn't make sense for us to allow null as a valid value for required primitives.

**Comment by yisraelU** [comment]
@Baccata you can switch it for option and it will still fail

**Comment by Baccata** [comment]
Oh, for optionals it's a different story, we would want for it to succeed with `None` instead of failing.

**Comment by yisraelU** [comment]
yeah that was my original case , I was just experimenting a bit with the example I posted,

**Comment by yisraelU** [comment]
i would also add for required fields, the message would benefit from being specialized considering the usage of null in Json 
```
PayloadError(.a, expected = String, message=Wrong Json shape)

```

**Comment by Baccata** [comment]
That can be another issue that would aim at improving error messages across the board when decoding documents. Feel free to open it with as good a description as possible :)

**Comment by kubukoz** [comment]
> Oh, for optionals it's a different story, we would want for it to succeed with None instead of failing.

I checked out of curiosity and that's what the JSON codecs do as well.

**Comment by Baccata** [comment]
@kubukoz you mean the JSON codecs have the correct behaviour ? It certainly [seem so](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/json/test/src/smithy4s/http/json/SchemaVisitorJCodecTests.scala#L144-L153)

**Comment by kubukoz** [comment]
yes, I meant the JSON codecs do it right (although I would've linked another test, one that doesn't involve defaults): https://github.com/disneystreaming/smithy4s/blob/4c9a81bfa609ef4a8adadccac7694a496882ec60/modules/json/test/src/smithy4s/http/json/SchemaVisitorJCodecTests.scala?rgh-link-date=2023-01-04T09%3A03%3A21Z#L161-L165

**Comment by zetashift** [comment]
Since this has a good-first-issue label I tried diving into this, just to make sure I am looking into the right spot:
The problem here is that
https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/core/src/smithy4s/Document.scala#L123
returns a `Left` no?

**Comment by kubukoz** [comment]
Yes, the decoder returned from `fromSchema` would return a `Left`, but for the fix I think you'll need to look inside

https://github.com/disneystreaming/smithy4s/blob/2961b9cd2b9abb60c89b8f8424f5da61546f6a5a/modules/core/src/smithy4s/internals/DocumentDecoderSchemaVisitor.scala#L297

which defines how struct decoders work.

**Comment by kubukoz** [comment]
minimal repro:

```scala
//> using scala "3.2.1"
//> using lib "com.disneystreaming.smithy4s::smithy4s-core:0.17.2"
import smithy4s.schema.Schema
import smithy4s.Document

@main def demo = println {
  val optionalFieldSchema =
    Schema
      .struct[Option[String]](Schema.string.optional[Option[String]]("test", identity))(identity)

  Document
    .Decoder
    .fromSchema(optionalFieldSchema)
    .decode(Document.obj("test" -> Document.DNull))
}

```

This currently prints `Left(PayloadError(.test, expected = String, message=Wrong Json shape))`, whereas it should be `Right(None)`.

**Comment by yisraelU** [comment]
@kubukoz did you mean to link to a different line?
That's the same function that @zetashift mentioned

**Comment by kubukoz** [comment]
lol, too many tabs. yes, fixing ;)

**Comment by zetashift** [comment]
Thank you! The function is a bit scarier than expected, but I'll try to get something working :p.
(And thanks for the minimal repro!)

**Comment by zetashift** [comment]
I feel like https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/core/src/smithy4s/internals/DocumentDecoderSchemaVisitor.scala#L327 this is the line that makes things go awry, but I have no idea what kind of logic is behind this. 
- `apply` gets in a `Schema[A]` and returns a `DocumentDecoder` for that `A`
- I am not sure how and why `(path, document)` is right next to it. 

EDIT: I'm also wondering if I, instead, add a `case Some(DNull) => ???` in the `fields.get(jLabel)` pattern mnatching and then something...

**Comment by yisraelU** [comment]
@zetashift 
Re:
"I am not sure how and why (path, document) is right next to it."
A DocumentDecoder has an apply method which takes a List[PayloadPath.Segment] and Document
The visitor apply returns a DocumentDecoder which is then applied to the path and document

**Comment by Baccata** [comment]
> EDIT: I'm also wondering if I, instead, add a case Some(DNull) => ??? in the fields.get(jLabel) pattern mnatching and then something...

I believe this is gonna be the correct fix. When encountering `Some(DNull)`, just add a `None` to the buffer, exactly like when encountering a `None`

**Comment by zetashift** [comment]
> > EDIT: I'm also wondering if I, instead, add a case Some(DNull) => ??? in the fields.get(jLabel) pattern mnatching and then something...
> 
> I believe this is gonna be the correct fix. When encountering `Some(DNull)`, just add a `None` to the buffer, exactly like when encountering a `None`

So last night, this was actually the first thing I did, but my test still failed. So that's why I wanted to discover the logic behind `buffer` and `apply` function..

Turns out..I wrote the test expecting a `Left(None)` instead of `Right(None)` 🤦.
I'll put up a PR soonish, thank you!!
