### ISSUE TITLE
[AWS] Create `AwsQueryInterpreter` 

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#720]
**This work should target the `feature/aws-query-protocol` branch**

 Same conceptual level as [here](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/aws/src/smithy4s/aws/internals/AwsJsonRPCInterpreter.scala)
 
The difference is that it'll amend the `Endpoint` (by creating a new instance of one) before passing it to the `AwsUnaryEndpoint`. The amendment will transform the schemas to add hints that will let the CodecAPI access additional information that's required during encoding.

#### Amendments to the input schema of the endpoint : 

The Input schema of the endpoint should be amended by the name the operation (accessible from its shapeId)  and the version property of the service (accessible from the smithy4s.Service interface). 

Hints carrying this information will have to be created, which can be done directly in Scala code (no need to create them in Smithy). Have a look at `InputOutput` to see a manually created hint. 

#### Amendments necessary to the AwsQueryCodecAPI

The `AwsQueryCodecAPI` will have to distinguish between when it's called for the input or for the output, in order to create a form-data encoder, or an xml decoder. This distinction can be achieved by inspect the hints of the Schema it receives for the `InputOutput` enumeration. 

This does imply that the `Codec` type member will have to change to carry something like `Either[FormDataEncoder, XmlDecoder]`. It'll be okay to throw an error if we're asked to decode something when we have a Left, or asked to encode something with a Right : this codecAPI should never be accessed by users directly and should very much move to an internal package and become package-private. 

When serialising inputs, this information will need to be added to the FormData before rendering : See https://smithy.io/2.0/aws/protocols/aws-query-protocol.html#request-serialization

#### Regarding the wiring the the Xml decoding 

Regarding the invocation of the XmlDecoder in the `CodecAPI`, you can have a look at [this](https://github.com/disneystreaming/smithy4s/blob/feature/aws-query-protocol/modules/xml/test/src/smithy4s/xml/XmlCodecSpec.scala#L565-L574). You'll have to create a stream from a `Chunk[Byte]` wrapping the `Array[Byte]` you receive from the CodecAPI

**Comment by Baccata** [comment]
@igor-ramazanov, do you think you'll be able to pick this ?

**Comment by igor-ramazanov** [comment]
@Baccata Hi, yes.

**Comment by igor-ramazanov** [comment]
@Baccata 

Used [aws-query traits](https://smithy.io/2.0/aws/protocols/aws-query-protocol.html) by grepping through https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models:
1. `cors` - unused
2. `endpoint` - ???
3. `hostLabel` - unused, perhaps, the `endpoint` is unused too, since they used together
4. `xmlAttribute` - unused
5. `xmlFlattened` - used by `sqs.json`
6. `xmlName` - used by many services
7. `xmlNamespace` - used by many services
8. `timestampFormat` - unused
9. `awsQueryError` - used by many services

So, used and unsupported (the highest priority):
1. `xmlNamespace`
2. `awsQueryError`

Unused and unsupported:
1. `endpoint` - ???

Used and supported:
1. `xmlAttribute`
2. `xmlFlattened`
3. `xmlName`

Unused and supported:
1. `cors`
2. `hostLabel`
3. `timestampFormat`

**Comment by igor-ramazanov** [comment]
So, I guess the `awsQueryError` and `xmlNamespace` are good ones to focus on if we want to deliver AWS Query.

Good one to focus on afterwards: `endpoint`.

And would be great still to verify that the rest is actually supported as well - I've only checked supported traits by grepping through the smithy4s codebase, doesn't really mean if actually supported or not: `cors`, `hostLabel`, `timestampFormat`.

The `xmlName`, `xmlFlattened` and `xmlName` are definitely supported as I saw them in your tests.

**Comment by igor-ramazanov** [comment]
I think it's a good idea to pull and run automatically protocol compliance tests from https://github.com/awslabs/smithy/tree/main/smithy-aws-protocol-tests/model/awsQuery.

**Comment by Baccata** [comment]
> cors, hostLabel, timestampFormat 

* cors in not officially supported but we document out to achieve this. If it was used in the context of AWS we could probably achieve it 
* timestampFormat is definitely supported 
* hostLabel is not supported at this time, but if it comes to that it'd be easy to support, in a similar way that we support `httpLabel`

> I think it's a good idea to pull and run automatically protocol compliance tests from 

Yup, we even have the [infrastructure](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/compliance-tests/src/smithy4s/compliancetests/HttpProtocolCompliance.scala#L31) to run them. This [issue](https://github.com/disneystreaming/smithy4s/issues/730) is a requirement though, as running the tests require the ability to produce a [FunctorAlgebra](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/compliance-tests/src/smithy4s/compliancetests/ReverseRouter.scala#L36), which is not currently what the AwsClient are, but we can shoe-horn them into a FunctorAlgebra shape to run the tests on them (or to make it more convenient for users to use for services that do not involve much streaming)

**Comment by Baccata** [comment]
Closing in favour of https://github.com/disneystreaming/smithy4s/issues/944 : the internals have been completely restructured in an effort to facilitate the implementation of additional protocols on top of http4s.
