### ISSUE TITLE
[AWS] Devise a way to test signature parity between the official AWS Java SDK and the smithy4s AWS SDK

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#722]
Something that's really hard to test is the assessment that the signature algorithm works correctly. 

What we should do is run our AWS requests and requests performed by the AWS Java SDK (reconfigured to call upon an http4s client) against a mock http4s backend that'll intercept the requests metadata and communicate to the test via some Ref or Deferred. 

This should give us some confidence that the signature algorithm is correctly implemented. We can target specific methods of specific services, and add to them as we go.

**Comment by daddykotex** [comment]
Isn't there a way to generate the signature that'd be use w/o actually making http calls? If so it could be setup in unit tests and be easier to debug/fix, etc.

**Comment by Baccata** [comment]
It's hard to do, because the signature depends on the fact that the inputs are correctly serialised in http payloads and headers. They also depend on us retrieving the correct metadata from the service specification, which is part of the signature.

**Comment by kubukoz** [comment]
> the AWS Java SDK (reconfigured to call upon an http4s client)

how do you even do this?? Seems like there'd be some work required to translate their request model into http4s, which sounds... like too much. Maybe we can just override the AWS endpoint to hit a local http4s server and capture requests this way?

**Comment by Baccata** [comment]
> how do you even do this 

in the sdk v2 you can override the http client, just need to implement some interface

**Comment by kubukoz** [comment]
right, so you have to translate. Maybe I'm overestimating how much effort that is.

**Comment by daddykotex** [comment]
Maybe you don't have to overwrite or re-implement the client but just point it to a mock service you'd spin up on a given port?

**Comment by kubukoz** [comment]
> Maybe we can just override the AWS endpoint to hit a local http4s server and capture requests this way?

that's what I meant here

**Comment by Baccata** [comment]
customising the client is lighter-weight cause it can run fully in memory without exercising the tcp layer

**Comment by Baccata** [comment]
plus from what I remember it's not that complicated

**Comment by daddykotex** [comment]
Ok so I got a pretty good testing ground. When I run the code, I can easily retrieve the headers added by the AWS SDK as well as the version built on Smithy4s generated code. For example, when I run for a `listTable` dynamodb operation, I get the following `Authorization` header (added newline for clarity):

For AWS:
```
AWS4-HMAC-SHA256
Credential=ASIA*************/20230123/us-east-1/dynamodb/aws4_request
SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-security-token;x-amz-target
Signature=85cd43c8a196fb95d9bb07a97ac9268a0dcf8174cc08fed*************
```

For Smithy4s
```
AWS4-HMAC-SHA256
Credential=asia*************/20230123/us-east-1/dynamodb/aws4_request
SignedHeaders=content-type;host;x-amz-date;x-amz-security-token;x-amz-target
Signature=c4a9a23cb31cdc4592f395be443bb23d948803c6712ea8a*************
```

Quick differences:
1. casing difference in the credential part (I don't think it changes anything from a request perspective but it could affect the hash ?)
2. signed headers are different

From here I'm not sure what we should be going for. For example, can we write a test suite that ensures both generate the SAME header?

**Comment by kubukoz** [comment]
I'd check for just significant differences, if order isn't supposed to matter in a header we shouldn't have to get the same order in our impl.

**Comment by Baccata** [comment]
> From here I'm not sure what we should be going for. For example, can we write a test suite that ensures both generate the SAME header? 

Mmm, I don't remember the Java SDK using all those traits to sign stuff. I think what we're gonna need to do is extract the `signedHeaders` information (and the corresponding headers value) and run them through a manual invocation of the signature algorithm to ensure we get the same thing as the SDK, because we'll probably never produce these following headers during the normal invocation of our SDK : `amz-sdk-invocation-id;amz-sdk-request` 

> I'd check for just significant differences, if order isn't supposed to matter in a header we shouldn't have to get the same order in our impl.

@daddykotex don't listen to @kubukoz, he doesn't know what he's talking about in this instance :trollface: Order does matter in this case, it's lexicographic order actually.

I think the comparison should check that for the subset of headers that appear in `signedheaders` list, we have the same value as the AWS SDK.

**Comment by kubukoz** [comment]
> @daddykotex don't listen to @kubukoz, he doesn't know what he's talking about in this instance :trollface: Order does matter in this case, it's lexicographic order actually.

which is why I said `if order isn't supposed to matter` :) should've been clearer that this should be checked in the docs

**Comment by Baccata** [comment]
Addressed in https://github.com/disneystreaming/smithy4s/pulls?q=is%3Apr+is%3Aclosed+signature
