### ISSUE TITLE
[AWS] Write a transformation that turns `AwsCall[F, I, E, O, SI, SO]` into `F[O]`

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#730]
[AwsCall](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/aws/src/smithy4s/aws/AwsCall.scala#L20) is a construct that captures all type parameters involved in the interaction with AWS SDKs. This construct is required as it allows to handle the various kinds of interactions and combinations of unary/streamed requests/responses. 

The way it works is that an implicit evidence is required when calling one of the methods held by this construct, to prove that the interaction is handle-able in a unary-fashion, or to prove that it has a stream component to it. 

This way of doing things is explained by the fact that the generated interfaces are homogenous in context types : we cannot have some methods that return an `F` and others that return something else. 

However, once we have an instance of an algebra that works against `AwsCall`, it would be nice to easily turn it into an algebra that works against `F`. 

Smithy4s defines several higher-kinded functor typeclasses, in particular [FunctorK5](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/core/src-3/generated/kinds/functorK.scala#L44-L46) , which is implemented by the companion objects of [all generated services](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/example/src/smithy4s/example/FooService.scala#L47).

So what the implementor of this ticket needs to write is something like : 

```scala
import smithy4s.kinds._ 

def forceUnary[Alg[_[_,_,_,_,_]], F[_]](service: Service[Alg]) : PolyFunction5[AwsCall[F, *,*,*,*,*], kind1[F]#toKind5]
``` 

Which uses the schemas of the endpoint associated to the call to produce the evidence required to call `.run` on the `AwsCall`, obtaining an `F`. If no such endpoint can be provided, an error should be raised in `F`. 

For inspiration, you can look at [this](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/core/src/smithy4s/Transformation.scala#L85-L97) implementation, which is used to turn an algebra that works against a monofunctor into an algebra that works against a bifunctor, utilising the information of the endpoints to know which errors are associated to which operation.

**Comment by yisraelU** [comment]
@Baccata 
What did you mean by `schemas of the endpoint associated to the call `
Is this function supposed to have access to the AwsUnaryEndpoint ?

**Comment by Baccata** [comment]
Mmm it shouldn't have access to the `AwsUnaryEndpoint` but I think I brain-farted and `PolyFunction5` is not what should be returned. The signature should be more like : 

```scala 
def simplify[Alg[_[_, _, _, _, _]], F[_]](service: Service[Alg]) : service.Interpreter[AwsCall[F, *, *, *, *, *]] => service.FunctorInterpreter[F] 
```

You can take inspiration from the [AbsorbError](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/core/src/smithy4s/Transformation.scala#L101-L120) transformation for instance. It's conceptually similar.

**Comment by yisraelU** [comment]
Oh, well that changes everything...

**Comment by kubukoz** [comment]
I was also a bit disappointed to see it can't be just a `PolyFunction5` 😅
