### ISSUE TITLE
Handle NaN/Infinity/-Infinity in the AWS protocols

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#760]
See https://smithy.io/2.0/aws/protocols/aws-json-1_1-protocol.html#shape-serialization

[This is where](https://github.com/disneystreaming/smithy4s/blob/series/0.17/modules/aws/src/smithy4s/json/AwsSchemaVisitorJCodec.scala) the code should be amended. 

[This is the implementation](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L580-L603)

The reason we're not doing this in the "standard" implementation is performance related.

**Comment by zetashift** [comment]
Is it okay if I pick this up?

**Comment by Baccata** [comment]
Very much so :)
