### ISSUE TITLE
Generate member Scaladoc for structs that don't have their own documentation

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#771]
After #731, if you try to generate code from

```smithy
$version: "2"

namespace demo

structure Hello {
  /// the field
  field: String
}
```

then you get this:

```scala
package demo

/* imports omitted */
case class Hello(field: Option[String] = None)
object Hello extends ShapeTag.Companion[Hello] {
/* omitted */
}
```

However, if you add docs to `Hello` itself:

```diff
namespace demo
 
+/// the struct
 structure Hello {
   /// the field
   field: String

```

then you get full-blown docs on the struct:

```scala
/** the struct
  * @param field
  *   the field
  */
case class Hello(field: Option[String] = None)
```

## Expectation

I think the behavior with the original Smithy snippet should be that the struct gets this Scaladoc:

```scala
/** @param field
  *   the field
  */
```

**Comment by daddykotex** [comment]
I'm not sure I follow, you intentionally want to discard the documentation message: `the struct`?

**Comment by kubukoz** [comment]
no, that doesn't exist in the original snippet.

I want this:

```smithy
structure Hello {
  /// the field
  field: String
}
```

to be generated as:

```scala
/** @param field
  *   the field
  */
case class Hello(field: Option[String] = None)
```

because currently it's:

```scala
case class Hello(field: Option[String] = None)
```

**Comment by kubukoz** [comment]
(I'm 90% sure) This happens because the following code doesn't look at `memberDocs` if there's no `Documentation` trait on the struct:

https://github.com/disneystreaming/smithy4s/blob/f81b362b6531272b454ee0e21b9567e9688bf7ba/modules/codegen/src/smithy4s/codegen/internals/SmithyToIR.scala#L782-L785

**Comment by daddykotex** [comment]
ahhh I see, I missed the initial comment inside of `Hello`.

**Comment by zetashift** [comment]
> (I'm 90% sure) This happens because the following code doesn't look at `memberDocs` if there's no `Documentation` trait on the struct:
> 
> https://github.com/disneystreaming/smithy4s/blob/f81b362b6531272b454ee0e21b9567e9688bf7ba/modules/codegen/src/smithy4s/codegen/internals/SmithyToIR.scala#L782-L785

Yeah I think this is correct, if `shape.getTrait` returns an empty value we'll get a None. Not sure how to write out an elegant, `if shape.getTrait.orElse(hasMemberTraits)` specifically for everything that is not a `union` or a `enum` or a `collection`.

**Comment by msosnicki** [comment]
I can have a look into it
