### ISSUE TITLE
Generate method documentation for operations

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#772]
Another follow-up to #731.

## Reproduction

Generate code for this spec:

```smithy
$version: "2"

namespace demo

service HelloService {
  operations: [GetHello]
}

/// op
operation GetHello {
  input: Hello
}

/// the struct
structure Hello {
  /// the field
  field: String
}
```

## Current behavior

The generated operation looks like this

```scala
  /** op */
  def getHello(field: Option[String] = None): F[Hello, Nothing, Unit, Nothing, Nothing]
```

## Expectation

Operations would have their inputs documented using `@param` annotations (just like structures that have these members):

```scala
  /** op
    * @param field
    *   the field
    */
  def getHello(field: Option[String] = None): F[Hello, Nothing, Unit, Nothing, Nothing]
```

this should also avoid the issue from #771, and generate `@param` docs even if the operation itself isn't documented.

**Comment by msosnicki** [comment]
I'll give it a go

**Comment by Baccata** [comment]
Be mindful of the fact that operations can have `packed` inputs. The behaviour when they are packed should probably be the same as it is right now 

https://disneystreaming.github.io/smithy4s/docs/codegen/customisation/packed-inputs
