### ISSUE TITLE
Create `Builder` data classes for `Service` and `Endpoint`

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#836]
Context : https://github.com/disneystreaming/smithy4s/pull/832#issuecomment-1446002920

Let's create `Endpoint.Builder` and `Service.Builder` data classes that can be easily access from `Endpoint` and `Service`, that would facilitate the manipulation and transformation of `Endpoint` and `Service`

They should follow the [Scala best practice around binary compatibility](https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html#changing-a-case-class-definition-in-a-backwards-compatible-manner).  

We could enhance the UX of using builders by having `mapX` methods for every element.

**Comment by kubukoz** [comment]
Looks like @GaryAghedo is on this.
