### ISSUE TITLE
[Core] DateTime with Offset is not parsed 

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#841]
According to the Smithy spec
https://smithy.io/2.0/spec/protocol-traits.html#smithy-api-timestampformat-trait
>Date time as defined by the date-time production in [RFC 3339#section-5.6](https://tools.ietf.org/html/rfc3339.html#section-5.6) with no UTC offset and optional fractional precision (for example, 1985-04-12T23:20:50.52Z). **However, offsets are parsed gracefully, but the datetime is normalized to an offset of zero by converting to UTC.**

https://github.com/disneystreaming/smithy4s/blob/e3f01daeb3016bcac1ec5682b83885a0c4f7e5c5/modules/core/src-jvm-native/smithy4s/Timestamp.scala#L265

**Comment by yisraelU** [comment]
cc @plokhotnyuk

**Comment by Baccata** [comment]
I'm pretty sure this detail was added rather recently. 

Andriy, if you can find the time to adjust the implementation (or give us pointers), that'd be awesome.

**Comment by yisraelU** [comment]
the clarification indeed is recent
https://github.com/awslabs/smithy/pull/1597

**Comment by plokhotnyuk** [comment]
I will add this feature for `Timestamp.parseDateTime`.

Please just confirm that `series/0.17` is a proper branch for the PR.

**Comment by kubukoz** [comment]
@plokhotnyuk that sounds right. Assuming this doesn't break existing code.

**Comment by plokhotnyuk** [comment]
Please review: https://github.com/disneystreaming/smithy4s/pull/844
