### ISSUE TITLE
Make operation return error type fail in compile.

### ISSUE THREAD

**Issue by andrewrigas** [disneystreaming/smithy4s#863]
So, recently I had this problem with my code which I spend some time debugging and I would like to see it raised in compile time if it's possible.

I have this smithy file for Illustration, where I have an operation that takes a string and returns 200. The service though should be able to fail with these `errors: [ ServiceUnavailable, BadRequest ]`. As you would see in the smithy file, I have missed the BadRequest to be included in the `errors:` section.

```smithy
$version: "2.0"

namespace dev.scala.smithy

use alloy#simpleRestJson

@simpleRestJson
service SimpleService {
    version: "1.0.0"
    operations: [SimpleOperation]
}

@http(method: "POST", uri: "/operation", code: 200)
operation SimpleOperation {
    input: InputData,
    errors: [ServiceUnavailable]
}

structure InputData {
    @required
    value: String,
}

@error("client")
@httpError(400)
structure BadRequest {
    code: Integer = 400
    message: String = "The request contains bad syntax or cannot be fulfilled."
}

@error("server")
@httpError(503)
structure ServiceUnavailable {
    code: Integer = 503
    message: String = "The server is currently unavailable."
}
```

In my scala code though I have included the BadRequest error, which that will lead to an UnknownErrorResponse.

```scala
object SimpleServiceIO extends SimpleService[IO] {

  override def simpleOperation(value: String): IO[Unit] =
    value.trim.toLowerCase() match {
      case "unavailable" =>
        IO.raiseError(ServiceUnavailable())
      case "bad" =>
        IO.raiseError(BadRequest())
      case _ => IO.unit
    }
}
```

I don't have any good suggestions or easy ones, but I would definitely like to see my code above failing at compile time because is not either catchable when service is tested locally. Maybe instead of having F[A] for the output we should introduce F[Either[Throwable, A]].

```scala
  override def simpleOperation(value: String): IO[Either[SimpleOperationError,Unit]] = ??? 
```

Any ideas?

**Comment by kubukoz** [comment]
Hi! Thanks for the examples, this was very helpful.

You can have "typed" errors thanks to `ErrorAware`:

```scala
import dev.scala.smithy._
import cats.effect.IO
import dev.scala.smithy.SimpleServiceGen.SimpleOperationError
import dev.scala.smithy.SimpleServiceGen.SimpleOperationError.ServiceUnavailableCase

type BIO[+E, +A] = IO[Either[E, A]]

object SimpleServiceIO extends SimpleService.ErrorAware[BIO] {

  override def simpleOperation(value: String): BIO[SimpleOperationError, Unit] =
    value.trim.toLowerCase() match {
      case "unavailable" => IO.pure(Left(ServiceUnavailableCase(ServiceUnavailable())))
      // this wouldn't compile, as you can't wrap BadRequest in any "*Case" subtype of SimpleOperationError
      // case "bad"         => IO.pure(Left(BadRequest()))
      case _ => IO.pure(Right(()))
    }

}
```

That way, you have the type safety if you don't use `IO.raise`. However, you still need to convert this to the "throwing" variant if you want to make a server. That's also possible:

```scala

def routes =
  SimpleRestJsonBuilder
    .routes(
      SimpleServiceIO.transform(new Transformation.AbsorbError[BIO, IO] {

        def apply[E, A](
          fa: BIO[E, A],
          injectError: E => Throwable,
        ): IO[A] = fa.flatMap(_.fold(e => IO.raiseError(injectError(e)), IO.pure))

      })
    )
    .resource
```

This feature is [documented](https://disneystreaming.github.io/smithy4s/docs/guides/smithy4s-transformations#error-related-transformations), but if anything is still unclear don't hesitate to ask!

Also, if you're on Scala 3, you can avoid the boilerplate of the `ServiceUnavailableCase` wrapping with [a metadata entry](https://disneystreaming.github.io/smithy4s/docs/codegen/customisation/error-unions).

**Comment by andrewrigas** [comment]
@kubukoz Thank you for your reply, I probably missed that in docs or went through it but didn't get it, really appreciate it :)

**Comment by kubukoz** [comment]
No worries, the docs are a little bit scattered and the search isn't perfect either ;)
