### ISSUE TITLE
Idea: formatting task in sbt/mill plugins

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#885]
Given the Language Server now supports formatting, we could have a task in each plugin that runs formatting on the Smithy sources. Like the LSP, this would use the formatter from [smithy-translate](https://github.com/disneystreaming/smithy-translate).

Additionally, there could be one that _checks_ that the files are formatted, and fails otherwise.

**Comment by Baccata** [comment]
Won't do : this is out of scope and I don't want to add a dependency just for a formatting task that can be done from other tools (editors or CLIs)
