### ISSUE TITLE
Add refinement provider for IdRef

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#889]
`@idRef` is a Smithy standard trait that you can put on a `String` type to ensure it's a valid Smithy shape.

Although schemas don't have access to all the possible shapes, we could at least provide a refinement that a value tagged with the trait uses valid shape syntax, in a typed way.

It would be something like this:

```scala
implicit val shapeIdRefinemend =
    Refinement
      .drivenBy[IdRef]
      .apply(ShapeId.parse(_: String).toRight("Not a valid ShapeId"), (_: ShapeId).show)
```

This would also be nice to special-case at codegen time, so that the `String` type would automatically become a `ShapeId` in the generated code - just like a custom refinement would change the type of any other primitive. This would be source breaking in the generated code, and possibly binary breaking for generated `smithy.api` code in smithy4s.

**Comment by Baccata** [comment]
Happy for this to be picked up.
