### ISSUE TITLE
Proposal: bake `Required` trait into the `.required` method on schemas

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#890]
In generated struct schemas, a field needs 2 things to be considered required:

- `.addHints(Required())`
- `.required`

```scala
case class SubscriptionCreated(subscriptionId: String)
object SubscriptionCreated extends ShapeTag.Companion[SubscriptionCreated] {
//...
  implicit val schema: Schema[SubscriptionCreated] = struct(
    string.required[SubscriptionCreated]("subscriptionId", _.subscriptionId).addHints(smithy.api.Required()),
  ){
    SubscriptionCreated.apply
  }.withId(id).addHints(hints)
}
```

I find this a bit strange - could we instead build `.addHints(Required)` into the `required` method and filter the trait out? Alternatively, we could avoid the special case but still have the hint added within `.required` to make it easier to handcraft these schemas, without complicating the codegen code.

**Comment by Baccata** [comment]
> a field needs 2 things to be considered required 

I don't think that's true, a field is considered required by virtue of being a required field. The fact that the `Required` trait is present on the field is just an artifact of the code-generation, because we haven't filter it out. 

We could prevent its rendering altogether, it shouldn't hurt tbh
