### ISSUE TITLE
Make generated case classes `final`

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#913]
As per the title.

**Comment by jgoday** [comment]
Hi @kubukoz, I'm starting to look at smithy and smithy4s.
About this issue,
I just started to look at the basecode,
It seems to me that the problem should be located in codegen.Renderer -> renderProductNonMixin,
(unions and products should be covered by that).

Am I missing any other consideration on this issue?
(sorry for asking or if it is not related, but I prefer to make sure before doing any PR)

**Comment by kubukoz** [comment]
@jgoday don't be sorry, it's actually great that you asked before spending time on it ;)

> It seems to me that the problem should be located in codegen.Renderer -> renderProductNonMixin, (unions and products should be covered by that).

Yes, that sounds reasonable, but I think you'll also need to do `renderUnion` and `renderOperation` too - pretty much every `case class` in the generated code should be final.

To try out your changes, you should be able to just run `example/compile` in sbt - that module contains some generated sources (which are tracked by git) so you'll see a nice diff quite quickly.

btw. I think you should base this work off of the `series/0.18` branch, this may be a breaking change so we probably won't make it in 0.17.

**Comment by jgoday** [comment]
Thank you @kubukoz , I have created a PR #924.

**Comment by Baccata** [comment]
Addressed in #924
