### ISSUE TITLE
`httpResponseCode` - `intEnum` support

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#915]
The `httpResponseCode` trait can be added to a member targetting an `intEnum` shape. Currently, smithy4s doesn't support this:

```smithy
$version: "2"

namespace hello

use alloy#simpleRestJson

@simpleRestJson
service WeatherService {
    operations: [GetWeather]
}

@http(method: "GET", uri: "/weather/{city}", code: 200)
@readonly
operation GetWeather {
    input := {
        @required
        @httpLabel
        city: String
    }
    output := {
        @required
        weather: String
        @required
        @httpResponseCode
        code: MyCode
    }
}

intEnum MyCode {
    NICE = 420
}
```

Hitting a service that uses this spec results in the status code not being reflected in the response:

```
[info] Status: 200 OK
[info] Body: {"weather":"bad weather in London","code":420}
```

Reproduction (`sbt run` starts a server and calls it with a client): https://github.com/kubukoz/demos/tree/smithy4s-http4s-responsecode-server

In most likelihood this is just because enums aren't handled in `HttpResponseCodeSchemaVisitor`.

**Comment by kubukoz** [comment]
Clients fail in even more spectacular ways when they try to deal with that response (status is 200, but the body has `code:420`):

```
[error] java.lang.ClassCastException: class java.lang.Integer cannot be cast to class hello.MyCode (java.lang.Integer is in module java.base of loader 'bootstrap'; hello.MyCode is in unnamed module of loader 'app')
```

**Comment by jgoday** [comment]
Hi @kubukoz, I was looking at this issue,
as you commented earlier,
seems to me that would be enough implementing enumeration in HttpResponseCodeSchemaVisitor.
using total: E => EnumValue[E] to convert enum value to httpResponse int value.

I have been able to try your demo example, and seems to work (it returns 420 as status code).
 
Where should I put both httpResponse and HttpResponseCodeSchemaVisitor tests ?
Edit: forget about it as @yisraelU already created a PR :)

**Comment by kubukoz** [comment]
now that's what I call a race condition 😅

**Comment by yisraelU** [comment]
@jgoday happy to close my pr in favor of yours especially since I didnt write tests :)

**Comment by jgoday** [comment]
> @jgoday happy to close my pr in favor of yours especially since I didnt write tests :)

@yisraelU don't worry, I didn't know where to put the test anyway :)

**Comment by kubukoz** [comment]
I think we usually put them in the same package as the class/object being tested, just in the test configuration
