### ISSUE TITLE
`@httpResponseCode` - client handling of 4xx/5xx codes

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#916]
Related: #915

This might be intentional, but clients are unable to decode a response when a `@httpResponseCode` value falls into the 4xx/5xx range:

```smithy
$version: "2"

namespace hello

use alloy#simpleRestJson

@simpleRestJson
service WeatherService {
    operations: [GetWeather]
}

@http(method: "GET", uri: "/weather/{city}", code: 200)
@readonly
operation GetWeather {
    input := {
        @required
        @httpLabel
        city: String
    }
    output := {
        @required
        weather: String
        @required
        @httpResponseCode
        code: Integer
    }
}
```

```scala
package hello

import cats.effect.IO
import cats.effect.IOApp
import hello.WeatherService
import org.http4s.ember.client.EmberClientBuilder
import org.http4s.ember.server.EmberServerBuilder
import smithy4s.http4s.SimpleRestJsonBuilder

object Main extends IOApp.Simple {
  def run = SimpleRestJsonBuilder
    .routes(
      new WeatherService[IO] {
        def getWeather(city: String): IO[GetWeatherOutput] =
          IO.pure(GetWeatherOutput("bad weather in " + city, 420))
      }
    )
    .resource
    .flatMap { routes =>
      EmberServerBuilder
        .default[IO]
        .withHttpApp(routes.orNotFound)
        .build
    }
    .flatMap { server =>
      EmberClientBuilder
        .default[IO]
        .build
        .flatMap { c =>
          SimpleRestJsonBuilder(WeatherService)
            .client(c)
            .uri(server.baseUri)
            .resource
            .evalMap {
              _.getWeather("London").flatMap(IO.println(_))
            }
        }
    }
    .use_
}

```

```
[error] smithy4s.http.UnknownErrorResponse: status 420, headers: Map(Date -> Thu, 20 Apr 2023 , Connection -> keep-alive, Content-Length -> 46, Content-Type -> application/json), body:
[error] {"weather":"bad weather in London","code":420}
```

Is this the expected behavior, or should the client still succeed in its call, giving the caller the ability to inspect the response themselves?

Full repro: https://github.com/kubukoz/demos/tree/smithy4s-916

**Comment by Baccata** [comment]
This behaviour is very much expected : arguably it's an oversight of AWS to not have specified that it should only be used for successful status codes. 

`httpStatusCode` falls in a gray area in that it very much leaks protocol details in domain-land. Users should not expect for non-success status code to be received. 

Arguably one could argue that AWS should very much constraint the targets of members carrying `@httpStatusCode` to be integer enumerations and for all the values to be between 200 and 299.

**Comment by kubukoz** [comment]
> IMO this seems like an HTTP spec thing and not a Smithy thing that needs to be explicitly documented in Smithy. I recommend failing to send the response.

This is about codes outside the 100-999 range, but I think it applies to the error case as well.

https://github.com/awslabs/smithy/issues/1116

**Comment by kubukoz** [comment]
I guess if there's any action point on our side, I guess we should also fail to serialize that response if we get something outside of `200-399`?

**Comment by Baccata** [comment]
>  I guess we should also fail to serialize that response if we get something outside of 200-399 ? 

Rather than fail I'd say just avoid setting the status code that comes from the encoded metadata if it's not in that range. That way the effective status code would be whatever is set by the endpoint.

**Comment by Baccata** [comment]
Setting the fixing of this to target 0.18 because I don't see it as very critical. 

EDIT : the fix would be a `.filter` call here : https://github.com/disneystreaming/smithy4s/blob/series/0.18/modules/http4s-kernel/src/smithy4s/http4s/kernel/MessageEncoder.scala#L74

**Comment by daddykotex** [comment]
I'm working on the http response / request model and I think this issue can be closed as this is fixed

But to be clear: current http4s will apply metadata code only if it's successful, so the actual range is `100 <= code <= 399`

is that all right with everyone?

**Comment by kubukoz** [comment]
Looks right to me.

**Comment by kubukoz** [comment]
just to be clear @daddykotex, is that fixed in 0.18 or 0.17?

**Comment by daddykotex** [comment]
0.18

**Comment by daddykotex** [comment]
might be an easy backport though, the fix is  simple but might be in a different location

**Comment by kubukoz** [comment]
I don't think it's particularly pressing for my team so I'll leave the choice up to you ;)
