### ISSUE TITLE
[Http4s] Content-Type conflict

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#969]
An Issue arises when there is a conflict between the media type defined in the CodecApi and a member of a struct that has a `httpHeader` trait setting the Content-Type on it.

- This is a problem  in the StringAndBlobSchemaVisitor which allows the MediaType to be dynamic and derived from the schema
For example: 

```smithy
structure MyStructure {
    @httpHeader("Content-Type")
    contentType: String,

    @httpPayload
    data: Blob
}
```
This is caused by setting the content type using the EntityEncoder from http4s `withContentType` .
- This is also a problem in simpleRestJson , as it causes the httpHeader trait to be ignored when using it for Content-Type
- Aso I would add that changing the order of  the arguments to  [`combine` ](https://github.com/disneystreaming/smithy4s/blob/bf4989f0751a2775b1bd4425f7691a90518b8dd7/modules/http4s-kernel/src/smithy4s/http4s/kernel/MessageEncoder.scala#L179) method , would change this behavior which did take me by surprise

**Comment by kubukoz** [comment]
Combine was never commutative I think, if you have functions that override the same field you can't just compose them in both directions

**Comment by yisraelU** [comment]
> Combine was never commutative I think, if you have functions that override the same field you can't just compose them in both directions

Yeah , my question is really at a different level . My understanding was an EntityEncoder dealt with the body only and the Metadata Encoder dealt with Header only, and therefore there would be no conflict .
However, Entity Encoder does affect the header/metadata

**Comment by yisraelU** [comment]
edited explanation of what surprised me

**Comment by kubukoz** [comment]
related: https://github.com/disneystreaming/smithy4s/issues/28 https://github.com/disneystreaming/smithy4s/pull/29

**Comment by yisraelU** [comment]
fixed
