### ISSUE TITLE
[SimpleRestJson] Question: Should we include empty headers 

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#971]
In the RestJson1 protocol headers are dropped when the value is one of `null`, empty string, or empty collection
Should this be implemented in simpleRestJson ?

**Comment by Baccata** [comment]
Can you share the corresponding test ?

**Comment by yisraelU** [comment]
@Baccata https://github.com/awslabs/smithy/blob/24abf76268955ea642f9cc5811f3adb3de7b2f8f/smithy-aws-protocol-tests/model/restJson1/http-headers.smithy#L415
