### ISSUE TITLE
[RestJson1] - Dense collections must be flexible with regards to receiving json null values

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#972]
See tests over [here](https://github.com/awslabs/smithy/blob/aca7df7daf31a0e71aebfeb2e72aee06ff707568/smithy-aws-protocol-tests/model/restJson1/json-maps.smithy#L425) 
i.e RestJsonDeserializesDenseSetMapAndSkipsNull
- Current behavior: passing in null where a collection is expected results in a json decoding `  Expected JSON array,`

**Comment by Baccata** [comment]
This behaviour should be :

* parameterised as an opt-in at the level of the relevant SchemaVisitor (in a way that is respectful to hot-paths when disabled) 
* enabled in the case of AWS protocols 
* disabled in the case of the SimpleRestJson protocol
