### ISSUE TITLE
[RestJson1] - Optional Payload  

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#973]
In the case ,that an optional payload is not present, an implementation should prepare for either an empty json object or  the lack of an HTTP body completely
See example test case [here](https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/restJson1/empty-input-output.smithy)

**Comment by Baccata** [comment]
I think the correct course of action would be to modify the decode methods in `JsonCodecAPI` to check so that if the payload is empty, `"{}".getBytes` is forwarded to the underlying jsoniter method.

**Comment by yisraelU** [comment]
@Baccata would you like this in the `simpleRestJson` protocol  too or just `restJson1`

**Comment by Baccata** [comment]
I think it's fine to have it as default in the json module, which would make it available in simpleRestJson
