### ISSUE TITLE
http4s middleware: provide semigroups

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#974]
`ServerEndpointMiddleware` and `ClientEndpointMiddleware` are glorified function wrappers, and currently the client/server builders only allow passing one of these.

In order to pass many, users have to combine them on their own, and I think we can make it simpler by providing semigroups out of the box (the types live in the http4s module which already has a cats dependency).

`Semigroup[ServerEndpointMiddleware]` would be equivalent to `(a, b) => a.andThen(b)`, same for client.

**Comment by zetashift** [comment]
Will it look like something like this(using scala 3 for now, can translate later to scala 2)?

```scala
//> using dep com.disneystreaming.smithy4s::smithy4s-http4s:0.17.6
//> using scala 3.3

import smithy4s.http4s.{ServerEndpointMiddleware, ClientEndpointMiddleware}
import cats.Semigroup

given semimid[F[_]]: Semigroup[ServerEndpointMiddleware[F]] with
  def combine(a: ServerEndpointMiddleware[F], b: ServerEndpointMiddleware[F]): ServerEndpointMiddleware[F] =
    a.andThen(b)
```

I don't know how to define `andThen` though, or where to start looking for hints for its implementation.

**Comment by kubukoz** [comment]
you don't _really_ need to define an `andThen`, but if you consider `ServerEndpointMiddleware` to be a function then you can implement that `combine` like you'd combine functions. I think it'll go like this:

```scala
//> using dep com.disneystreaming.smithy4s::smithy4s-http4s:0.17.6
//> using scala 3.3
import smithy4s.Endpoint
import org.http4s.HttpApp
import smithy4s.Service

import smithy4s.http4s.ServerEndpointMiddleware
import smithy4s.http4s.ClientEndpointMiddleware
import cats.Semigroup

given semimid[F[_]]: Semigroup[ServerEndpointMiddleware[F]] with

  def combine(
    a: ServerEndpointMiddleware[F],
    b: ServerEndpointMiddleware[F],
  ): ServerEndpointMiddleware[F] =
    new ServerEndpointMiddleware[F] {

      override def prepare[Alg[_[_, _, _, _, _]]](
        service: Service[Alg]
      )(
        endpoint: Endpoint[service.Operation, ?, ?, ?, ?, ?]
      ): HttpApp[F] => HttpApp[F] =
        a
          .prepare(service)(endpoint)
          .andThen(b.prepare(service)(endpoint))

    }
```
