### ISSUE TITLE
[RestJson1] - Sparse trait implementation

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#990]
[Docs](https://smithy.io/2.0/spec/type-refinement-traits.html#smithy-api-sparse-trait)
The sparse trait indicates that a list or map may have a null as a value.

Given that our target language is Scala , I am not sure how to approach implementation.
I would have liked to simply drop any nulls when deserializing a list, however, this makes the codec non-round-trippable.
Also, this would raise a question should the implementation for Map be different as a key cannot be null and therefore a key mapped to null can be used to signal some information 

Another option would be to have the hint affect the codegen (like the meta traits we have) and produce a List[Option[A]]

**Comment by kubukoz** [comment]
I wouldn't want to expose users to nulls. If anything, I'd hide them under some newtype (e.g. `SparseList[A]` with a `def get(index): Option[A]`) or go with `List[Option[A]]` like you mentioned.

Also worth pointing out, this would affect all 4 sequence types (list/indexedseq/vector/set) in addition to maps.

**Comment by yisraelU** [comment]
>Also worth pointing out, this would affect all 4 sequence types (list/indexedseq/vector/set) in addition to maps.

yes, of course , I am referring to Smithy types of which there is only List and Map
