### ISSUE TITLE
How to return an empty Integer, Double, etc... as a null in json response

### ISSUE THREAD

**Issue by colomain** [disneystreaming/smithy4s#991]
Hello,
I have a business requirement that forces me to return values of type Double, Integer, etc... as null when they are empty, instead of not appearing in the response

Example:

instead of

```json
{
    "data": [
        {
            "id": 1
        }
    ]
}
```

I want to achieve:

```json
{
    "data": [
        {
            "id": 1,
            "nullableField": null
        }
    ]
}
```

How can I achieve this without having to specify `nullableField` as a `Document`?

I know how to do it with `Document` (and convert Json value to Document...), but this way, swagger specification got misleading, and `nullableField` appears as an object (without type).

Thank you!

**Comment by kubukoz** [comment]
I don't think there's a baked in way to do this with `simpleRestJson`. I think you could create a new protocol, or at least a new protocol builder for `simpleRestJson`, which would use a custom `JsonCodecAPI` implementation that configures the jsoniter `WriterConfig` to write nulls. However, that's going to be a global setting for all Smithy services that use that builder, so you won't have the ability to do this on a case-by-case basis.

**Comment by lewisjkl** [comment]
Hey @colomain, what @kubukoz suggested will definitely work for you, but I was just chatting with @Baccata and we have a way that we can add a configuration to the SimpleRestJson builder that would indicate that all optional fields with a `None` value should be encoded as `null` rather than omitting the field. I should be able to have a PR up later today or tomorrow that addresses this.

**Comment by colomain** [comment]
Awesome!! Thx @lewisjkl !

**Comment by daddykotex** [comment]
See the PR attached @colomain 

You should get support for that in the next 0.17 release.

**Comment by daddykotex** [comment]
This was release as part of [0.17.8](https://github.com/disneystreaming/smithy4s/releases/tag/v0.17.8)
